Feature: 03.1 Enquiry Management

  @SmokeRegressionTC1_1 @2childenquiry @CRMAddNP @Register @SmokeRegressionTC1_1 @Test
  Scenario Outline: DataCreationInRedfish_Verify if redfish Enquiry Booking, Child, Notes, Nursery and Visit are created in redfish is automatically created in CRM
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify if the web page title actual "<expectedtitle>"
    And In home page verify if Enquiries and Enquiry in the main menu
    When Clicked on menu item "<MainMenuItem>" and submenu "<SubMenuItem>"
    Then Verify if the web page submenu title is "<expectedenqtitle>"
    When Parent First Name "<ParentFirstName>" Parent Second Name "<ParentSecondName>" Address "<Address>" Postcode "<Postcode>" MobileNumber "<MobileNumber>" Email id "<EmailId>"
    When The source is selected as "<Source>"
    When The First Child First Name "<FirstChildFirstName>" First Child Second Name "<SecondChildSecondName>" First Child DOB "<DOB>" Gender "<FirstChildGender>" Enrolment Start Date "<FirstEnrolmentStartDate>"
    When First child Booking Patten is "<BookingPatten>"
    When The Second Child First Name "<SecondChildFirstName>" Second Child Second Name "<SecondChildSecondName>" First Child DOB "<SecondChildDOB>" Gender "<SecondChildGender>" Enrolment Start Date "<SecondEnrolmentStartDate>"
    When Second Child Booking Patten is "<SecondBookingPatten>"
    Then Click on Add Enquiry
    Then Submit General Notes "<ParentName>"
    When Verify if user can add a visit with visit date "<VisitDate>" and visit time "<VisitTime>" with main comment "<ParentSecondName>"
    Then Logout from redfish and close browser

    Examples: 
      | UserName    | Password  | application | expectedtitle | MainMenuItem | SubMenuItem | expectedenqtitle | ParentFirstName | ParentSecondName | ParentName       | Address                 | Postcode | MobileNumber | EmailId                    | Source     | FirstChildFirstName | SecondChildSecondName | DOB        | FirstChildGender | FirstEnrolmentStartDate | FirstEnrolmentEndDate | BookingPatten | SecondChildFirstName | SecondChildSecondName | SecondChildDOB | SecondChildGender | SecondEnrolmentStartDate | SecondBookingPatten | EnquiryDetails  | Sibling | Relationship | ParentalResponsibility | PhotoPreference | TFCReference | LEAFEETReference | hrFundingCode | ChildProfileTitle | VisitDate  | VisitTime |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Jana            | Schoenfisch      | Jana Schoenfisch | 99-2190 St. Marys Road  | SO93 0LG |  07944582830 | jschoenfisch3f@webnode.com | BH Website | Thorn               | Schoenfisch           | 15/01/2018 | M                | 01/12/2020              | 12/12/2022            | All Days      | Obidiah              | Schoenfisch           | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000239 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Gery            | Jurries          | Gery Jurries     | 99-2191 St. Marys Road  | SO93 0LG |  07710994769 | gjurries3g@discuz.com      | BH Website | Mitchael            | Jurries               | 15/01/2018 | M                | 01/12/2020              | 12/12/2022            | All Days      | Howie                | Jurries               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000240 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Giustina        | Godsell          | Giustina Godsell | 99-2192 St. Marys Road  | SO94 0LG |  07859516650 | ggodsell3h@youtube.com     | BH Website | Dorrie              | Godsell               | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Gallagher            | Godsell               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000241 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Floyd           | Longhi           | Floyd Longhi     | 99-2193 St. Marys Road  | SO95 0LG |  07781482324 | flonghi3i@princeton.com    | BH Website | Linell              | Longhi                | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Hayden               | Longhi                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000242 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Hart            | Buie             | Hart Buie        | 99-2194 St. Marys Road  | SO96 0LG |  07539439782 | hbuie3j@a8.com             | BH Website | Celeste             | Buie                  | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Willdon              | Buie                  | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000243 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Mitch           | Cabble           | Mitch Cabble     | 99-21895 St. Marys Road | SO97 0LG |  07934077237 | mcabble3k@weebly.com       | BH Website | Elysia              | Cabble                | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Alister              | Cabble                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000244 | Child             | 21/01/2020 |      0930 |

  @CRMAddNP
  Scenario Outline: DataCreationInCRM_Verify if user is able to add a new Nursery Preference for an enquiry in CRM
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters RedfishCRM User Name "<UserName>" and Password "<Password>"
    Then Verify if the RedfishCRM web page title actual "<expectedtitle>"
    Then Verify if user able to search with parent email id "<ParentEmailID>" "<contactfilename>" "<ParentName>"
    Then Verify if user able to open the enquiry and verify the title as "<CRMEnquiryTitle>" screenshot in "<Enquiryfilename>"
    Then Verify if user is able to add "<Nursery>" in nursery preferred
    Then Logout from redfishCRM and close browser "<CRMlogoutfilename>"

    Examples: 
      | UserName                    | Password | application | expectedtitle                                             | ParentEmailID           | Postcode | ParentFirstName | ParentSecondName | ParentName         | EnquiryType | InvalidSearch | MobileNumber | contactfilename          | contactwithenqfilename      | CRMlogoutfilename              | CRMEnquiryTitle          | Enquiryfilename          | Nursery                                  | CRMVisitTitle      | Visitfilename          | FullNameFileName           | ParentEmailIDFileName                | Postcodefilename     | InvalidSearchFilename    | contactviewfilename    |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | amccomec0@telegraph.com | SO78 0LG | Alexine         | McCome           | Alexine McCome     | RedFish     | @#$           |  07879519460 | contactAlexineMcCome     | contactenqAlexineMcCome     | contactlogoutAlexineMcCome     | Enquiry: RedFish Enquiry | EnquiryAlexineMcCome     | Northwick Park Day Nursery and Preschool | Appointment: Visit | VisitAlexineMcCome     | FullNameAlexine McCome     | ParentEmailIDamccomec0@telegraph.com | PostcodefileSO78 0LG | InvalidsearchAlexine     | contactviewAlexine     |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | llarterc1@naver.com     | SO79 0LG | Luciano         | Larter           | Luciano Larter     | RedFish     | 14/10/2020    |  07953429162 | contactLucianoLarter     | contactenqLucianoLarter     | contactlogoutLucianoLarter     | Enquiry: RedFish Enquiry | EnquiryLucianoLarter     | Yellow Dot Ampfield                      | Appointment: Visit | VisitLucianoLarter     | FullNameLuciano Larter     | ParentEmailIDllarterc1@naver.com     | PostcodefileSO79 0LG | InvalidsearchLuciano     | contactviewLuciano     |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | emacmeanmac2@naver.com  | SO80 0LG | Editha          | MacMeanma        | Editha MacMeanma   | RedFish     | 901Editha     |  07279258624 | contactEdithaMacMeanma   | contactenqEdithaMacMeanma   | contactlogoutEdithaMacMeanma   | Enquiry: RedFish Enquiry | EnquiryEdithaMacMeanma   | Abbeymore Day Nursery and Preschool      | Appointment: Visit | VisitEdithaMacMeanma   | FullNameEditha MacMeanma   | ParentEmailIDemacmeanmac2@naver.com  | PostcodefileSO80 0LG | InvalidsearchEditha      | contactviewEditha      |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | jfeaverc3@google.com    | SO81 0LG | Julie           | Feaver           | Julie Feaver       | RedFish     | @#$           |  07504813697 | contactJulieFeaver       | contactenqJulieFeaver       | contactlogoutJulieFeaver       | Enquiry: RedFish Enquiry | EnquiryJulieFeaver       | Northwick Park Day Nursery and Preschool | Appointment: Visit | VisitJulieFeaver       | FullNameJulie Feaver       | ParentEmailIDjfeaverc3@google.com    | PostcodefileSO81 0LG | InvalidsearchJulie       | contactviewJulie       |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | zpardic4@sakura.com     | SO82 0LG | Zane            | Pardi            | Zane Pardi         | RedFish     | 14/10/2020    |  07553419964 | contactZanePardi         | contactenqZanePardi         | contactlogoutZanePardi         | Enquiry: RedFish Enquiry | EnquiryZanePardi         | Yellow Dot Ampfield                      | Appointment: Visit | VisitZanePardi         | FullNameZane Pardi         | ParentEmailIDzpardic4@sakura.com     | PostcodefileSO82 0LG | InvalidsearchZane        | contactviewZane        |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | sneilsonc5@go.com       | SO83 0LG | Sigrid          | Neilson          | Sigrid Neilson     | RedFish     | 901Sigrid     |  07469209115 | contactSigridNeilson     | contactenqSigridNeilson     | contactlogoutSigridNeilson     | Enquiry: RedFish Enquiry | EnquirySigridNeilson     | Abbeymore Day Nursery and Preschool      | Appointment: Visit | VisitSigridNeilson     | FullNameSigrid Neilson     | ParentEmailIDsneilsonc5@go.com       | PostcodefileSO83 0LG | InvalidsearchSigrid      | contactviewSigrid      |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | qdethloffc6@fc2.com     | SO84 0LG | Queenie         | Dethloff         | Queenie Dethloff   | RedFish     | @#$           |  07461504954 | contactQueenieDethloff   | contactenqQueenieDethloff   | contactlogoutQueenieDethloff   | Enquiry: RedFish Enquiry | EnquiryQueenieDethloff   | Northwick Park Day Nursery and Preschool | Appointment: Visit | VisitQueenieDethloff   | FullNameQueenie Dethloff   | ParentEmailIDqdethloffc6@fc2.com     | PostcodefileSO84 0LG | InvalidsearchQueenie     | contactviewQueenie     |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | jandinoc7@is.com        | SO85 0LG | Jacquenetta     | Andino           | Jacquenetta Andino | RedFish     | 14/10/2020    |  07288040166 | contactJacquenettaAndino | contactenqJacquenettaAndino | contactlogoutJacquenettaAndino | Enquiry: RedFish Enquiry | EnquiryJacquenettaAndino | Yellow Dot Ampfield                      | Appointment: Visit | VisitJacquenettaAndino | FullNameJacquenetta Andino | ParentEmailIDjandinoc7@is.com        | PostcodefileSO85 0LG | InvalidsearchJacquenetta | contactviewJacquenetta |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | cmcfiec8@vinaora.com    | SO86 0LG | Christie        | McFie            | Christie McFie     | RedFish     | 901Christie   |  07427861874 | contactChristieMcFie     | contactenqChristieMcFie     | contactlogoutChristieMcFie     | Enquiry: RedFish Enquiry | EnquiryChristieMcFie     | Abbeymore Day Nursery and Preschool      | Appointment: Visit | VisitChristieMcFie     | FullNameChristie McFie     | ParentEmailIDcmcfiec8@vinaora.com    | PostcodefileSO86 0LG | InvalidsearchChristie    | contactviewChristie    |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | slukovicc9@time.com     | SO87 0LG | Shell           | Lukovic          | Shell Lukovic      | RedFish     | 14/10/2020    |  07699081109 | contactShellLukovic      | contactenqShellLukovic      | contactlogoutShellLukovic      | Enquiry: RedFish Enquiry | EnquiryShellLukovic      | Northwick Park Day Nursery and Preschool | Appointment: Visit | VisitShellLukovic      | FullNameShell Lukovic      | ParentEmailIDslukovicc9@time.com     | PostcodefileSO87 0LG | InvalidsearchShell       | contactviewShell       |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | cdevonsca@hc360.com     | SO88 0LG | Case            | Devons           | Case Devons        | RedFish     | 901Case       |  07786200301 | contactCaseDevons        | contactenqCaseDevons        | contactlogoutCaseDevons        | Enquiry: RedFish Enquiry | EnquiryCaseDevons        | Yellow Dot Ampfield                      | Appointment: Visit | VisitCaseDevons        | FullNameCase Devons        | ParentEmailIDcdevonsca@hc360.com     | PostcodefileSO88 0LG |                          | contactviewCase        |

  @SmokeRegressionTC1_3 @Register
  Scenario Outline: Verify if user is able to register one child
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify if the web page title actual "<expectedtitle>"
    Then Verify search functionality with only Parent Name "<EmailId>" in search page
    Then Verify Enquiry search functionality with only Parent Name "<EmailId>" in search page
    When Clicked on register First child with sibling with "<Sibling>"
    When Selecting the Relationship status as "<Relationship>" and Parental Parental Responsibility as "<ParentalResponsibility>"
    When Selecting the PhotoPreference as "<PhotoPreference>"
    When The TFC Reference "<TFCReference>" and LEAFEETReference "<LEAFEETReference>" and hrFundingCode "<hrFundingCode>"
    When The Enrolment Leave date is "<FirstEnrolmentEndDate>"
    Then Verify if the child is registered "<ChildProfileTitle>"
    Then Logout from redfish and close browser

    Examples: 
      | UserName    | Password  | application | expectedtitle | MainMenuItem | SubMenuItem | expectedenqtitle | ParentFirstName | ParentSecondName | ParentName       | Address                 | Postcode | MobileNumber | EmailId                    | Source     | FirstChildFirstName | SecondChildSecondName | DOB        | FirstChildGender | FirstEnrolmentStartDate | FirstEnrolmentEndDate | BookingPatten | SecondChildFirstName | SecondChildSecondName | SecondChildDOB | SecondChildGender | SecondEnrolmentStartDate | SecondBookingPatten | EnquiryDetails  | Sibling | Relationship | ParentalResponsibility | PhotoPreference | TFCReference | LEAFEETReference | hrFundingCode | ChildProfileTitle | VisitDate  | VisitTime |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Jana            | Schoenfisch      | Jana Schoenfisch | 99-2190 St. Marys Road  | SO93 0LG |  07944582830 | jschoenfisch3f@webnode.com | BH Website | Thorn               | Schoenfisch           | 15/01/2018 | M                | 01/12/2020              | 12/12/2022            | All Days      | Obidiah              | Schoenfisch           | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000239 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Gery            | Jurries          | Gery Jurries     | 99-2191 St. Marys Road  | SO93 0LG |  07710994769 | gjurries3g@discuz.com      | BH Website | Mitchael            | Jurries               | 15/01/2018 | M                | 01/12/2020              | 12/12/2022            | All Days      | Howie                | Jurries               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000240 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Giustina        | Godsell          | Giustina Godsell | 99-2192 St. Marys Road  | SO94 0LG |  07859516650 | ggodsell3h@youtube.com     | BH Website | Dorrie              | Godsell               | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Gallagher            | Godsell               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000241 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Floyd           | Longhi           | Floyd Longhi     | 99-2193 St. Marys Road  | SO95 0LG |  07781482324 | flonghi3i@princeton.com    | BH Website | Linell              | Longhi                | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Hayden               | Longhi                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000242 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Hart            | Buie             | Hart Buie        | 99-2194 St. Marys Road  | SO96 0LG |  07539439782 | hbuie3j@a8.com             | BH Website | Celeste             | Buie                  | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Willdon              | Buie                  | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000243 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Mitch           | Cabble           | Mitch Cabble     | 99-21895 St. Marys Road | SO97 0LG |  07934077237 | mcabble3k@weebly.com       | BH Website | Elysia              | Cabble                | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Alister              | Cabble                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000244 | Child             | 21/01/2020 |      0930 |

  @Register @2ndRegister @Register
  Scenario Outline: Verify if user is able to register the 2nd Child
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify if the web page title actual "<expectedtitle>"
    Then Verify search functionality with only Parent Name "<EmailId>" in search page
    Then Verify Enquiry search functionality with only Parent Name "<EmailId>" in search page
    When Clicked on register Second child with sibling "<Sibling>"
    When Selecting the Relationship status as "<Relationship>" and Parental Parental Responsibility as "<ParentalResponsibility>"
    When Selecting the PhotoPreference as "<PhotoPreference>"
    When The TFC Reference "<TFCReference>" and LEAFEETReference "<LEAFEETReference>" and hrFundingCode "<hrFundingCode>"
    When The Enrolment Leave date is "<FirstEnrolmentEndDate>"
    Then Verify if the child is registered "<ChildProfileTitle>"
    Then Logout from redfish and close browser

    Examples: 
      | UserName    | Password  | application | expectedtitle | MainMenuItem | SubMenuItem | expectedenqtitle | ParentFirstName | ParentSecondName | ParentName       | Address                 | Postcode | MobileNumber | EmailId                    | Source     | FirstChildFirstName | SecondChildSecondName | DOB        | FirstChildGender | FirstEnrolmentStartDate | FirstEnrolmentEndDate | BookingPatten | SecondChildFirstName | SecondChildSecondName | SecondChildDOB | SecondChildGender | SecondEnrolmentStartDate | SecondBookingPatten | EnquiryDetails  | Sibling | Relationship | ParentalResponsibility | PhotoPreference | TFCReference | LEAFEETReference | hrFundingCode | ChildProfileTitle | VisitDate  | VisitTime |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Jana            | Schoenfisch      | Jana Schoenfisch | 99-2190 St. Marys Road  | SO93 0LG |  07944582830 | jschoenfisch3f@webnode.com | BH Website | Thorn               | Schoenfisch           | 15/01/2018 | M                | 01/12/2020              | 12/12/2022            | All Days      | Obidiah              | Schoenfisch           | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000239 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Gery            | Jurries          | Gery Jurries     | 99-2191 St. Marys Road  | SO93 0LG |  07710994769 | gjurries3g@discuz.com      | BH Website | Mitchael            | Jurries               | 15/01/2018 | M                | 01/12/2020              | 12/12/2022            | All Days      | Howie                | Jurries               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000240 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Giustina        | Godsell          | Giustina Godsell | 99-2192 St. Marys Road  | SO94 0LG |  07859516650 | ggodsell3h@youtube.com     | BH Website | Dorrie              | Godsell               | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Gallagher            | Godsell               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000241 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Floyd           | Longhi           | Floyd Longhi     | 99-2193 St. Marys Road  | SO95 0LG |  07781482324 | flonghi3i@princeton.com    | BH Website | Linell              | Longhi                | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Hayden               | Longhi                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000242 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Hart            | Buie             | Hart Buie        | 99-2194 St. Marys Road  | SO96 0LG |  07539439782 | hbuie3j@a8.com             | BH Website | Celeste             | Buie                  | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Willdon              | Buie                  | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000243 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Mitch           | Cabble           | Mitch Cabble     | 99-21895 St. Marys Road | SO97 0LG |  07934077237 | mcabble3k@weebly.com       | BH Website | Elysia              | Cabble                | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Alister              | Cabble                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000244 | Child             | 21/01/2020 |      0930 |

  @SmokeRegressionTC1_2
  Scenario Outline: DataVerificationInCRM_Verify if redfish Enquiry Booking, Child, Notes, Nursery and Visit are created in redfish is automatically created in CRM
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters RedfishCRM User Name "<UserName>" and Password "<Password>"
    Then Verify if the RedfishCRM web page title actual "<expectedtitle>"
    Then Verify if user able to search with parent email id "<ParentEmailID>" "<contactfilename>" "<ParentName>"
    Then Verify if Enquiry is created by taking the screen shot of the enquiry table "<contactwithenqfilename>"
    Then Verify if user able to open the enquiry and verify the title as "<CRMEnquiryTitle>" screenshot in "<Enquiryfilename>"
    Then Verify if user able to open the visit and verify the title as "<CRMVisitTitle>" screenshot in "<Visitfilename>"
    Then Logout from redfishCRM and close browser "<CRMlogoutfilename>"

    Examples: 
      | UserName                    | Password | application | expectedtitle                                             | ParentEmailID            | Postcode | ParentFirstName | ParentSecondName | ParentName       | EnquiryType | InvalidSearch | MobileNumber | contactfilename        | contactwithenqfilename    | CRMlogoutfilename            | CRMEnquiryTitle          | Enquiryfilename        | CRMVisitTitle      | Visitfilename        | FullNameFileName         | ParentEmailIDFileName                 | Postcodefilename     | InvalidSearchFilename | contactviewfilename |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | lashfoldgl@netscape.com  | SO38 0LG | Lezlie          | Tythacott        | Lezlie Tythacott | RedFish     | @#$           |  07214596965 | contactLezlieTythacott | contactenqLezlieTythacott | contactlogoutLezlieTythacott | Enquiry: RedFish Enquiry | EnquiryLezlieTythacott | Appointment: Visit | VisitLezlieTythacott | FullNameLezlie Tythacott | ParentEmailIDlashfoldgl@netscape.com  | PostcodefileSO38 0LG | InvalidsearchLezlie   | contactviewLezlie   |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | parentgm@theatlantic.com | SO39 0LG | Patin           | Blouet           | Patin Blouet     | RedFish     | 14/10/2020    |  07374096556 | contactPatinBlouet     | contactenqPatinBlouet     | contactlogoutPatinBlouet     | Enquiry: RedFish Enquiry | EnquiryPatinBlouet     | Appointment: Visit | VisitPatinBlouet     | FullNamePatin Blouet     | ParentEmailIDparentgm@theatlantic.com | PostcodefileSO39 0LG | InvalidsearchPatin    | contactviewPatin    |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | lgwylltgn@ebay.com       | SO40 0LG | Laural          | Langfield        | Laural Langfield | RedFish     | 901Laural     |  07727152892 | contactLauralLangfield | contactenqLauralLangfield | contactlogoutLauralLangfield | Enquiry: RedFish Enquiry | EnquiryLauralLangfield | Appointment: Visit | VisitLauralLangfield | FullNameLaural Langfield | ParentEmailIDlgwylltgn@ebay.com       | PostcodefileSO40 0LG | InvalidsearchLaural   | contactviewLaural   |

  @Register2Children
  Scenario Outline: DataVerificationInCRM_Verify if redfish Enquiry Booking, Child, Notes, Nursery and Visit are created in redfish is automatically created in CRM
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters RedfishCRM User Name "<UserName>" and Password "<Password>"
    Then Verify if the RedfishCRM web page title actual "<expectedtitle>"
    Then Verify if user able to search with parent email id "<ParentEmailID>" "<contactfilename>" "<ParentName>"
    Then Verify if Enquiry is created by taking the screen shot of the enquiry table "<contactwithenqfilename>"
    Then Verify if user able to open the enquiry and verify the title as "<CRMEnquiryTitle>" screenshot in "<Enquiryfilename>"
    Then Verify if user able to open the visit and verify the title as "<CRMVisitTitle>" screenshot in "<Visitfilename>"
    Then Logout from redfishCRM and close browser "<CRMlogoutfilename>"

    Examples: 
      | UserName                    | Password | application | expectedtitle                                             | ParentEmailID            | Postcode | ParentFirstName | ParentSecondName | ParentName       | EnquiryType | InvalidSearch | MobileNumber | contactfilename        | contactwithenqfilename    | CRMlogoutfilename            | CRMEnquiryTitle          | Enquiryfilename        | CRMVisitTitle      | Visitfilename        | FullNameFileName         | ParentEmailIDFileName                 | Postcodefilename     | InvalidSearchFilename | contactviewfilename |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | lashfoldgl@netscape.com  | SO38 0LG | Lezlie          | Tythacott        | Lezlie Tythacott | RedFish     | @#$           |  07214596965 | contactLezlieTythacott | contactenqLezlieTythacott | contactlogoutLezlieTythacott | Enquiry: RedFish Enquiry | EnquiryLezlieTythacott | Appointment: Visit | VisitLezlieTythacott | FullNameLezlie Tythacott | ParentEmailIDlashfoldgl@netscape.com  | PostcodefileSO38 0LG | InvalidsearchLezlie   | contactviewLezlie   |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | parentgm@theatlantic.com | SO39 0LG | Patin           | Blouet           | Patin Blouet     | RedFish     | 14/10/2020    |  07374096556 | contactPatinBlouet     | contactenqPatinBlouet     | contactlogoutPatinBlouet     | Enquiry: RedFish Enquiry | EnquiryPatinBlouet     | Appointment: Visit | VisitPatinBlouet     | FullNamePatin Blouet     | ParentEmailIDparentgm@theatlantic.com | PostcodefileSO39 0LG | InvalidsearchPatin    | contactviewPatin    |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | lgwylltgn@ebay.com       | SO40 0LG | Laural          | Langfield        | Laural Langfield | RedFish     | 901Laural     |  07727152892 | contactLauralLangfield | contactenqLauralLangfield | contactlogoutLauralLangfield | Enquiry: RedFish Enquiry | EnquiryLauralLangfield | Appointment: Visit | VisitLauralLangfield | FullNameLaural Langfield | ParentEmailIDlgwylltgn@ebay.com       | PostcodefileSO40 0LG | InvalidsearchLaural   | contactviewLaural   |

  @CRMPhoneEnquiry
  Scenario Outline: DataCreationInCRM_Verify if user is able to create a phone enquiry from CRM
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters RedfishCRM User Name "<UserName>" and Password "<Password>"
    Then Verify if the RedfishCRM web page title actual "<expectedtitle>"
    Then Verify if user is able to click on new contact and get the actual title "<expnewcontacttitle>"
    Then Type Parent First Name "<ParentFirstName>" Parent Second Name "<ParentSecondName>" Address "<Address>" Postcode "<Postcode>" MobileNumber "<MobileNumber>" Email id "<ParentEmailID>" Relationship Type "<relationshipType>"
    Then Take screen shot in file name "<NewContactfilename>"
    Then Logout from redfishCRM and close browser "<CRMlogoutfilename>"

    Examples: 
      | UserName                    | Password | application | expectedtitle                                             | expnewcontacttitle   | ParentFirstName | ParentSecondName | ParentName     | CRMlogoutfilename          | ParentEmailID              | Postcode | MobileNumber | NewContactfilename      | relationshipType |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | Contact: New Contact | Krista          | Moffett          | Krista Moffett | contactlogoutKristaMoffett | kmoffettel@independent.com | SO45 0LG |  07803935159 | NewContactKristaMoffett | Parent           |

  @SingleChildEnquiry @Regiser1Child @AbsenceCN @ADPTesting
  Scenario Outline: DataSingleChidlCreationInRedfish_Verify if redfish Enquiry Booking, Child, Notes, Nursery and Visit are created in redfish is automatically created in CRM
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify if the web page title actual "<expectedtitle>"
    And In home page verify if Enquiries and Enquiry in the main menu
    When Clicked on menu item "<MainMenuItem>" and submenu "<SubMenuItem>"
    Then Verify if the web page submenu title is "<expectedenqtitle>"
    When Parent First Name "<ParentFirstName>" Parent Second Name "<ParentSecondName>" Address "<Address>" Postcode "<Postcode>" MobileNumber "<MobileNumber>" Email id "<EmailId>"
    When The source is selected as "<Source>"
    When The First Child First Name "<FirstChildFirstName>" First Child Second Name "<SecondChildSecondName>" First Child DOB "<DOB>" Gender "<FirstChildGender>" Enrolment Start Date "<FirstEnrolmentStartDate>"
    When First child Booking Patten is "<BookingPatten>"
    Then Click on Add Enquiry
    Then Submit General Notes "<ParentName>"
    Then Logout from redfish and close browser

    Examples: 
      | UserName    | Password   | application | expectedtitle | MainMenuItem | SubMenuItem | expectedenqtitle | ParentFirstName | ParentSecondName | ParentName         | Address                | Postcode | MobileNumber | EmailId                  | Source     | FirstChildFirstName | SecondChildSecondName | DOB        | FirstChildGender | FirstEnrolmentStartDate | FirstEnrolmentEndDate | BookingPatten                   | SecondChildFirstName | SecondChildSecondName | SecondChildDOB | SecondChildGender | SecondEnrolmentStartDate | SecondBookingPatten | EnquiryDetails  | Sibling | Relationship | ParentalResponsibility | PhotoPreference | TFCReference | LEAFEETReference | hrFundingCode | ChildProfileTitle | VisitDate  | VisitTime |
      | 99160101NM  | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Nisse           | Legerwood        | Nisse Legerwood    | 309 Loomis Park        | SO50 0LG |  07984944162 | nlegerwood7l@utexas.com  | BH Website | Tammara             | Legerwood             | 15/01/2019 | M                | 03/01/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW FAM FPM | Obidiah              | Legerwood             | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Cornall         | Valler           | Cornall Valler     | 45 2nd Lane            | SO51 0LG |  07187810465 | cvaller7m@rakuten.com    | BH Website | Rosco               | Valler                | 15/01/2019 | M                | 08/03/2021              | 12/12/2022            | All Days                        | Howie                | Valler                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000014 | Child             | 21/01/2020 |      0930 |
      | 99160101NM3 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Amaleta         | Reyne            | Amaleta Reyne      | 47536 3rd Street       | SO52 0LG |  07830518497 | areyne7n@china.com       | BH Website | Pearl               | Reyne                 | 28/10/2017 | F                | 08/03/2021              | 12/12/2022            | AMM AMT PMT AMW PMW THAM THPM   | Gallagher            | Reyne                 | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000015 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Robers          | Spry             | Robers Spry        | 4895 Oriole Center     | SO53 0LG |  07400339596 | rspry7o@accuweather.com  | BH Website | Roxanna             | Spry                  | 15/01/2019 | F                | 01/03/2021              | 12/12/2022            | AMM PMM AMT PMT FAM FPM         | Hayden               | Spry                  | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000016 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Ossie           | Sara             | Ossie Sara         | 0237 Troy Parkway      | SO54 0LG |  07371983983 | osara7p@amazon.com       | BH Website | Twila               | Sara                  | 15/01/2019 | M                | 01/03/2021              | 12/12/2022            | AMM AMT AMW AMTH AMF PMM        | Willdon              | Sara                  | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000017 | Child             | 21/01/2020 |      0930 |
      | 99160101NM3 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Brenda          | Jiggins          | Brenda Jiggins     | 3 Leroy Plaza          | SO55 0LG |  07013686363 | bjiggins7q@microsoft.com | BH Website | Etienne             | Jiggins               | 15/01/2019 | M                | 09/03/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW         | Alister              | Jiggins               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000018 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Cher            | Muge             | Cher Muge          | 91268 Graedel Drive    | SO56 0LG |  07100422698 | cmuge7r@stanford.com     | BH Website | Nikolaus            | Muge                  | 15/01/2019 | F                | 03/01/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW FAM FPM | Obidiah              | Muge                  | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000019 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Luisa           | Andryszczak      | Luisa Andryszczak  | 71 Montana Avenue      | SO57 0LG |  07378055539 | landryszczak7s@mail.com  | BH Website | Pinchas             | Andryszczak           | 15/01/2019 | M                | 09/03/2021              | 12/12/2022            | AMT AMW PMW THAM THPM           | Howie                | Andryszczak           | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000020 | Child             | 21/01/2020 |      0930 |
      | 99160101NM3 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Shermie         | Sandels          | Shermie Sandels    | 1 Little Fleur Trail   | SO58 0LG |  07420074993 | ssandels7t@php.com       | BH Website | Yanaton             | Sandels               | 15/01/2019 | M                | 01/03/2021              | 12/12/2022            | All AM                          | Gallagher            | Sandels               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000021 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Major           | Heyworth         | Major Heyworth     | 026 Bluestem Junction  | SO59 0LG |  07752611104 | mheyworth7u@prweb.com    | BH Website | Reyna               | Heyworth              | 15/01/2019 | F                | 09/03/2021              | 12/12/2022            | AMT PMT AMW                     | Hayden               | Heyworth              | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000022 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Sydney          | Lambourn         | Sydney Lambourn    | 3 Scofield Road        | SO60 0LG |  07809250427 | slambourn7v@google.com   | BH Website | Denny               | Lambourn              | 15/01/2019 | M                | 01/03/2021              | 12/12/2022            | AMT THAM                        | Willdon              | Lambourn              | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000023 | Child             | 21/01/2020 |      0930 |
      | 99160101NM3 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Sax             | Pickance         | Sax Pickance       | 1 Melby Hill           | SO61 0LG |  07153009137 | spickance7w@tmall.com    | BH Website | Lora                | Pickance              | 15/01/2019 | F                | 09/03/2021              | 12/12/2022            | AMT PMT THAM THPM               | Alister              | Pickance              | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000024 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Tonia           | Frazer           | Tonia Frazer       | 97 Chive Junction      | SO62 0LG |  07227120897 | tfrazer7x@cbc.com        | BH Website | Clarie              | Frazer                | 28/10/2017 | M                | 01/03/2021              | 12/12/2022            | AMT THAM                        | Willdon              | Frazer                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000025 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Atlante         | Goakes           | Atlante Goakes     | 29747 Village Junction | SO63 0LG |  07750376324 | agoakes7y@imgur.com      | BH Website | Phyllida            | Goakes                | 15/01/2019 | F                | 01/03/2021              | 12/12/2022            | AMT PMT THAM THPM               | Alister              | Goakes                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000026 | Child             | 21/01/2020 |      0930 |
      | 99160101NM3 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Ronny           | De Francisci     | Ronny De Francisci | 00 Packers Plaza       | SO63 0LG |  07776415586 | rdefrancisci7z@wikia.com | BH Website | Timmy               | De Francisci          | 15/01/2019 | F                | 01/03/2021              | 12/12/2022            | AMT PMT THAM THPM               | Alister              | De Francisci          | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000026 | Child             | 21/01/2020 |      0930 |

  @RegisterSingleChild @Regiser1Child @AbsenceCN @ADPTesting
  Scenario Outline: Verify if user is able to register one child
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify if the web page title actual "<expectedtitle>"
    Then Verify search functionality with only Parent Name "<EmailId>" in search page
    Then Verify Enquiry search functionality with only Parent Name "<EmailId>" in search page
    When Clicked on register First child with sibling with "<Sibling>"
    When Selecting the Relationship status as "<Relationship>" and Parental Parental Responsibility as "<ParentalResponsibility>"
    When Selecting the PhotoPreference as "<PhotoPreference>"
    When The TFC Reference "<TFCReference>" and LEAFEETReference "<LEAFEETReference>" and hrFundingCode "<hrFundingCode>"
    When The Enrolment Leave date is "<FirstEnrolmentEndDate>"
    Then Verify if the child is registered "<ChildProfileTitle>"
    Then Logout from redfish and close browser

    Examples: 
      | UserName    | Password   | application | expectedtitle | MainMenuItem | SubMenuItem | expectedenqtitle | ParentFirstName | ParentSecondName | ParentName         | Address                | Postcode | MobileNumber | EmailId                  | Source     | FirstChildFirstName | SecondChildSecondName | DOB        | FirstChildGender | FirstEnrolmentStartDate | FirstEnrolmentEndDate | BookingPatten                   | SecondChildFirstName | SecondChildSecondName | SecondChildDOB | SecondChildGender | SecondEnrolmentStartDate | SecondBookingPatten | EnquiryDetails  | Sibling | Relationship | ParentalResponsibility | PhotoPreference | TFCReference | LEAFEETReference | hrFundingCode | ChildProfileTitle | VisitDate  | VisitTime |
      | 99160101NM  | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Nisse           | Legerwood        | Nisse Legerwood    | 309 Loomis Park        | SO50 0LG |  07984944162 | nlegerwood7l@utexas.com  | BH Website | Tammara             | Legerwood             | 15/01/2019 | M                | 03/01/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW FAM FPM | Obidiah              | Legerwood             | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Cornall         | Valler           | Cornall Valler     | 45 2nd Lane            | SO51 0LG |  07187810465 | cvaller7m@rakuten.com    | BH Website | Rosco               | Valler                | 15/01/2019 | M                | 08/03/2021              | 12/12/2022            | All Days                        | Howie                | Valler                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000014 | Child             | 21/01/2020 |      0930 |
      | 99160101NM3 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Amaleta         | Reyne            | Amaleta Reyne      | 47536 3rd Street       | SO52 0LG |  07830518497 | areyne7n@china.com       | BH Website | Pearl               | Reyne                 | 28/10/2017 | F                | 08/03/2021              | 12/12/2022            | AMM AMT PMT AMW PMW THAM THPM   | Gallagher            | Reyne                 | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000015 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Robers          | Spry             | Robers Spry        | 4895 Oriole Center     | SO53 0LG |  07400339596 | rspry7o@accuweather.com  | BH Website | Roxanna             | Spry                  | 15/01/2019 | F                | 01/03/2021              | 12/12/2022            | AMM PMM AMT PMT FAM FPM         | Hayden               | Spry                  | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000016 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Ossie           | Sara             | Ossie Sara         | 0237 Troy Parkway      | SO54 0LG |  07371983983 | osara7p@amazon.com       | BH Website | Twila               | Sara                  | 15/01/2019 | M                | 01/03/2021              | 12/12/2022            | AMM AMT AMW AMTH AMF PMM        | Willdon              | Sara                  | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000017 | Child             | 21/01/2020 |      0930 |
      | 99160101NM3 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Brenda          | Jiggins          | Brenda Jiggins     | 3 Leroy Plaza          | SO55 0LG |  07013686363 | bjiggins7q@microsoft.com | BH Website | Etienne             | Jiggins               | 15/01/2019 | M                | 09/03/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW         | Alister              | Jiggins               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000018 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Cher            | Muge             | Cher Muge          | 91268 Graedel Drive    | SO56 0LG |  07100422698 | cmuge7r@stanford.com     | BH Website | Nikolaus            | Muge                  | 15/01/2019 | F                | 03/01/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW FAM FPM | Obidiah              | Muge                  | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000019 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Luisa           | Andryszczak      | Luisa Andryszczak  | 71 Montana Avenue      | SO57 0LG |  07378055539 | landryszczak7s@mail.com  | BH Website | Pinchas             | Andryszczak           | 15/01/2019 | M                | 09/03/2021              | 12/12/2022            | AMT AMW PMW THAM THPM           | Howie                | Andryszczak           | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000020 | Child             | 21/01/2020 |      0930 |
      | 99160101NM3 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Shermie         | Sandels          | Shermie Sandels    | 1 Little Fleur Trail   | SO58 0LG |  07420074993 | ssandels7t@php.com       | BH Website | Yanaton             | Sandels               | 15/01/2019 | M                | 01/03/2021              | 12/12/2022            | All AM                          | Gallagher            | Sandels               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000021 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Major           | Heyworth         | Major Heyworth     | 026 Bluestem Junction  | SO59 0LG |  07752611104 | mheyworth7u@prweb.com    | BH Website | Reyna               | Heyworth              | 15/01/2019 | F                | 09/03/2021              | 12/12/2022            | AMT PMT AMW                     | Hayden               | Heyworth              | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000022 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Sydney          | Lambourn         | Sydney Lambourn    | 3 Scofield Road        | SO60 0LG |  07809250427 | slambourn7v@google.com   | BH Website | Denny               | Lambourn              | 15/01/2019 | M                | 01/03/2021              | 12/12/2022            | AMT THAM                        | Willdon              | Lambourn              | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000023 | Child             | 21/01/2020 |      0930 |
      | 99160101NM3 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Sax             | Pickance         | Sax Pickance       | 1 Melby Hill           | SO61 0LG |  07153009137 | spickance7w@tmall.com    | BH Website | Lora                | Pickance              | 15/01/2019 | F                | 09/03/2021              | 12/12/2022            | AMT PMT THAM THPM               | Alister              | Pickance              | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000024 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Tonia           | Frazer           | Tonia Frazer       | 97 Chive Junction      | SO62 0LG |  07227120897 | tfrazer7x@cbc.com        | BH Website | Clarie              | Frazer                | 28/10/2017 | M                | 01/03/2021              | 12/12/2022            | AMT THAM                        | Willdon              | Frazer                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000025 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1  | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Atlante         | Goakes           | Atlante Goakes     | 29747 Village Junction | SO63 0LG |  07750376324 | agoakes7y@imgur.com      | BH Website | Phyllida            | Goakes                | 15/01/2019 | F                | 01/03/2021              | 12/12/2022            | AMT PMT THAM THPM               | Alister              | Goakes                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000026 | Child             | 21/01/2020 |      0930 |
      | 99160101NM3 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Ronny           | De Francisci     | Ronny De Francisci | 00 Packers Plaza       | SO63 0LG |  07776415586 | rdefrancisci7z@wikia.com | BH Website | Timmy               | De Francisci          | 15/01/2019 | F                | 01/03/2021              | 12/12/2022            | AMT PMT THAM THPM               | Alister              | De Francisci          | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000026 | Child             | 21/01/2020 |      0930 |

  @CRMPhoneEnquiry
  Scenario Outline: DataCreationInCRM_Verify if user is able to create a phone enquiry from CRM
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters RedfishCRM User Name "<UserName>" and Password "<Password>"
    Then Verify if the RedfishCRM web page title actual "<expectedtitle>"
    Then Verify if user is able to click on new contact and get the actual title "<expnewcontacttitle>"
    Then Type Parent First Name "<ParentFirstName>" Parent Second Name "<ParentSecondName>" Address "<Address>" Postcode "<Postcode>" MobileNumber "<MobileNumber>" Email id "<ParentEmailID>" Relationship Type "<relationshipType>"
    Then Take screen shot in file name "<NewContactfilename>"
    Then Logout from redfishCRM and close browser "<CRMlogoutfilename>"

    Examples: 
      | UserName                    | Password | application | expectedtitle                                             | expnewcontacttitle   | ParentFirstName | ParentSecondName | ParentName     | CRMlogoutfilename          | ParentEmailID              | Postcode | MobileNumber | NewContactfilename      | relationshipType |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | Contact: New Contact | Krista          | Moffett          | Krista Moffett | contactlogoutKristaMoffett | kmoffettel@independent.com | SO45 0LG |  07803935159 | NewContactKristaMoffett | Parent           |

  @CRMAddNP
  Scenario Outline: DataCreationInCRM_Verify if user is able to add a new Nursery Preference for an enquiry in CRM
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters RedfishCRM User Name "<UserName>" and Password "<Password>"
    Then Verify if the RedfishCRM web page title actual "<expectedtitle>"
    Then Verify if user able to search with parent email id "<ParentEmailID>" "<contactfilename>" "<ParentName>"
    Then Verify if user able to open the enquiry and verify the title as "<CRMEnquiryTitle>" screenshot in "<Enquiryfilename>"
    Then Verify if user is able to add "<Nursery>" in nursery preferred
    Then Logout from redfishCRM and close browser "<CRMlogoutfilename>"

    Examples: 
      | UserName                    | Password | application | expectedtitle                                             | expnewcontacttitle   | ParentFirstName | ParentSecondName | ParentName       | CRMlogoutfilename          | ParentEmailID               | Postcode | MobileNumber | NewContactfilename        | Address                | relationshipType | CRMEnquiryTitle          | Enquiryfilename        | Nursery                                  | contactfilename        |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | Contact: New Contact | Neddy           | Gairdner         | Neddy Gairdner   | contactlogoutNeddyGairdner | ngairdnerea@telegraph.com   | SO54 0LG |  07749636857 | NewContactNeddyGairdner   | 99-2154 St. Marys Road | Parent           | Enquiry: RedFish Enquiry | EnquiryNeddyGairdner   | Northwick Park Day Nursery and Preschool | contactNeddyGairdner   |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | Contact: New Contact | Elsworth        | Nias             | Elsworth Nias    | contactlogoutElsworthNias  | eniaseb@hexun.com           | SO55 0LG |  07975285568 | NewContactElsworthNias    | 99-2155 St. Marys Road | Parent           | Enquiry: RedFish Enquiry | EnquiryElsworthNias    | Yellow Dot Ampfield                      | contactElsworthNias    |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | Contact: New Contact | Fulvia          | Edmonston        | Fulvia Edmonston | Edmonston Fulvia Edmonston | fedmonstonec@soundcloud.com | SO56 0LG |  07256642122 | NewContactFulviaEdmonston | 99-2156 St. Marys Road | Parent           | Enquiry: RedFish Enquiry | EnquiryFulviaEdmonston | Abbeymore Day Nursery and Preschool      | contactFulviaEdmonston |

  @AddAbsenceSingleChild @AbsenceCN @RegressionMar21
  Scenario Outline: Verify if user is able to add Absence for a child
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify search functionality with only Parent Name "<EmailId>" in search page
    Then Verify Child search functionality with only Parent Email id "<EmailId>" in search page
    Then Verify if your able to click on Absence link and key in the Start Date "<AbsenceStartDate>" and End Date "<AbsenceEndDate>"
    When Verify if the Absence Reason is selected as "<AbsenceReason>" and Add absence
    Then Logout from redfish and close browser

    Examples: 
      | UserName | Password   | application | expectedtitle | MainMenuItem | SubMenuItem | expectedenqtitle | ParentFirstName | ParentSecondName | ParentName         | EmailId                     | AbsenceStartDate | AbsenceEndDate | AbsenceReason                               |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Grace           | Hexum            | Grace Hexum        | ghexum2m@blinklist.com      | 4/3/2021         | 8/3/2021       | COVID-19 Family Choice Non-Chargeable       |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Camey           | Davidovitz       | Camey Davidovitz   | cdavidovitz2n@usnews.com    | 5/3/2021         | 15/03/2021     | COVID-19 Family Choice Non-Chargeable       |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Nike            | Tongs            | Nike Tongs         | ntongs2o@answers.com        | 5/3/2021         | 10/3/2021      | COVID-19 Family Choice Non-Chargeable       |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Virgina         | Eiler            | Virgina Eiler      | veiler2p@yelp.com           | 5/3/2021         | 12/3/2021      | COVID-19 Family Choice Non-Chargeable       |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Leon            | Kilfedder        | Leon Kilfedder     | lkilfedder2q@amazon.com     | 6/3/2021         | 15/03/2021     | COVID-19 Family Choice Non-Chargeable       |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Aggie           | Chatainier       | Aggie Chatainier   | achatainier2r@digg.com      | 6/3/2021         | 15/03/2021     | COVID-19 Family Choice Non-Chargeable       |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Clarinda        | Reinmar          | Clarinda Reinmar   | creinmar2s@netvibes.com     | 18/03/2021       | 21/03/2021     | COVID-19 Family Choice Non-Chargeable       |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Burke           | Eltune           | Burke Eltune       | beltune2t@w3.com            | 18/03/2021       | 25/03/2021     | COVID-19 Family Choice Non-Chargeable       |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Ardine          | Ough             | Ardine Ough        | aough2u@umn.com             | 9/3/2021         | 12/3/2021      | COVID-19 Family Choice Non-Chargeable       |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Vilhelmina      | Berzins          | Vilhelmina Berzins | vberzins2v@diigo.com        | 9/3/2021         | 12/3/2021      | COVID-19 Nursery Restriction Non-Chargeable |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Isidoro         | Stout            | Isidoro Stout      | istout2w@huffingtonpost.com | 14/03/2021       | 28/03/2021     | COVID-19 Family Choice Non-Chargeable       |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Cody            | Klemt            | Cody Klemt         | cklemt2x@hp.com             | 11/3/2021        | 15/03/2021     | COVID-19 Family Choice Non-Chargeable       |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Salim           | Hanby            | Salim Hanby        | shanby2y@indiatimes.com     | 14/03/2021       | 28/03/2021     | COVID-19 Family Choice Non-Chargeable       |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Leigh           | Battrick         | Leigh Battrick     | lbattrick2z@aboutads.com    | 11/3/2021        | 15/03/2021     | COVID-19 Family Choice Non-Chargeable       |

  @ManagementLaunchInvoicing
  Scenario Outline: Verify if user is able to run the Automatic Task for Launch Invoicing
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify if user is able to click on management link in the main menu
    Then Verify if is able to click on Automatic Tasks link in management page
    Then Verify if user is able to select the invoice month "<InvoiceMonth>" year "<InvoiceYear>" and Launch Invoicing
    Then Logout from redfish and close browser

    Examples: 
      | UserName | Password   | application | InvoiceMonth | InvoiceYear |
      | 99160101 | Password01 | redfishUAT  |            3 |        2021 |

  @AbsenceCreditNoteTask
  Scenario Outline: Verify if user is able to run the Automatic Task for Launch Invoicing
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify if user is able to click on management link in the main menu
    Then Verify if is able to click on Automatic Tasks link in management page
    Then Verify if user is able click on Absence Credit Note Task
    Then Logout from redfish and close browser

    Examples: 
      | UserName | Password   | application | InvoiceMonth | InvoiceYear |
      | 99160101 | Password01 | redfishUAT  |            1 |        2021 |

  @AddExtraSessions @AbsenceCN @RegressionMar21
  Scenario Outline: Verify if user is able to add Extra Session for a child
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify search functionality with only Parent Name "<EmailId>" in search page
    Then Verify Child search functionality with only Parent Email id "<EmailId>" in search page
    Then Verify if user is able to click on Extra Sesssion link
    Then Verify if user is able to type the Extra Sessions Date "<ExtraSessionsDate>" Booking Pattern "<ExtraSessionsBookingPattern>" and click on Add
    Then Logout from redfish and close browser

    Examples: 
      | UserName | Password   | application | expectedtitle | MainMenuItem | SubMenuItem | expectedenqtitle | ParentFirstName | ParentSecondName | ParentName         | EmailId                     | ExtraSessionsDate | ExtraSessionsBookingPattern |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Grace           | Hexum            | Grace Hexum        | ghexum2m@blinklist.com      | 4/3/2021          | Full day                    |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Camey           | Davidovitz       | Camey Davidovitz   | cdavidovitz2n@usnews.com    | 4/3/2021          | Full day                    |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Nike            | Tongs            | Nike Tongs         | ntongs2o@answers.com        | 12/3/2021         | AM                          |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Virgina         | Eiler            | Virgina Eiler      | veiler2p@yelp.com           | 3/3/2021          | PM                          |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Leon            | Kilfedder        | Leon Kilfedder     | lkilfedder2q@amazon.com     | 1/3/2021          | PM                          |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Aggie           | Chatainier       | Aggie Chatainier   | achatainier2r@digg.com      | 3/11/2021         | Full day                    |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Clarinda        | Reinmar          | Clarinda Reinmar   | creinmar2s@netvibes.com     | 18/03/2021        | AM                          |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Burke           | Eltune           | Burke Eltune       | beltune2t@w3.com            | 15/03/2021        | PM                          |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Ardine          | Ough             | Ardine Ough        | aough2u@umn.com             | 28/02/2021        | Full day                    |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Vilhelmina      | Berzins          | Vilhelmina Berzins | vberzins2v@diigo.com        | 15/03/2021        | Full day                    |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Isidoro         | Stout            | Isidoro Stout      | istout2w@huffingtonpost.com | 15/03/2021        | AM                          |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Cody            | Klemt            | Cody Klemt         | cklemt2x@hp.com             | 15/03/2021        | PM                          |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Salim           | Hanby            | Salim Hanby        | shanby2y@indiatimes.com     | 15/03/2021        | Full day                    |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Leigh           | Battrick         | Leigh Battrick     | lbattrick2z@aboutads.com    | 15/03/2021        | AM                          |

  @AddDiscounts @AbsenceCN @RegressionMar21
  Scenario Outline: Verify if user is able to add Add Discounts for a child
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify search functionality with only Parent Name "<EmailId>" in search page
    Then Verify Child search functionality with only Parent Email id "<EmailId>" in search page
    Then Verify if user is able to click on Discount link
    Then Verify if user is able to add a discount with Start Date "<DiscountStartDate>" End Date "<DiscountEndDate>" NameRate "<NameRate>" and Order "<Order>"
    Then Logout from redfish and close browser

    Examples: 
      | UserName | Password   | application | expectedtitle | MainMenuItem | SubMenuItem | expectedenqtitle | ParentFirstName | ParentSecondName | ParentName         | EmailId                     | DiscountStartDate | DiscountEndDate | NameRate                             | Order |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Grace           | Hexum            | Grace Hexum        | ghexum2m@blinklist.com      | 01/03/2021        | 31/03/2021      | 10% Sibling Discount  / 10%          |     1 |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Camey           | Davidovitz       | Camey Davidovitz   | cdavidovitz2n@usnews.com    | 01/03/2021        | 31/03/2021      | 40% Staff Discount / 40%             |    99 |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Nike            | Tongs            | Nike Tongs         | ntongs2o@answers.com        | 01/03/2021        | 31/03/2021      | 100% COVID Government Closure / 100% |     1 |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Virgina         | Eiler            | Virgina Eiler      | veiler2p@yelp.com           | 01/03/2021        | 31/03/2021      | 10% Sibling Discount  / 10%          |    99 |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Leon            | Kilfedder        | Leon Kilfedder     | lkilfedder2q@amazon.com     | 01/03/2021        | 31/03/2021      | 40% Staff Discount / 40%             |     1 |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Aggie           | Chatainier       | Aggie Chatainier   | achatainier2r@digg.com      | 01/03/2021        | 31/03/2021      | 100% COVID Government Closure / 100% |    99 |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Clarinda        | Reinmar          | Clarinda Reinmar   | creinmar2s@netvibes.com     | 01/03/2021        | 31/03/2021      | 10% Sibling Discount  / 10%          |     1 |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Burke           | Eltune           | Burke Eltune       | beltune2t@w3.com            | 01/03/2021        | 31/03/2021      | 40% Staff Discount / 40%             |    99 |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Ardine          | Ough             | Ardine Ough        | aough2u@umn.com             | 01/03/2021        | 31/03/2021      | 100% COVID Government Closure / 100% |     1 |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Vilhelmina      | Berzins          | Vilhelmina Berzins | vberzins2v@diigo.com        | 01/03/2021        | 31/03/2021      | 10% Sibling Discount  / 10%          |    99 |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Isidoro         | Stout            | Isidoro Stout      | istout2w@huffingtonpost.com | 01/03/2021        | 31/03/2021      | 40% Staff Discount / 40%             |     1 |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Cody            | Klemt            | Cody Klemt         | cklemt2x@hp.com             | 01/03/2021        | 31/03/2021      | 100% COVID Government Closure / 100% |    99 |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Salim           | Hanby            | Salim Hanby        | shanby2y@indiatimes.com     | 01/03/2021        | 31/03/2021      | 40% Staff Discount / 40%             |     1 |
      | 99160101 | Password01 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Leigh           | Battrick         | Leigh Battrick     | lbattrick2z@aboutads.com    | 01/03/2021        | 31/03/2021      | 100% COVID Government Closure / 100% |    99 |
