Feature: 03.1 Enquiry Management

  @SmokeRegressionTC1_1 @2childenquiry @CRMAddNP @Register
  Scenario Outline: DataCreationInRedfish_Verify if redfish Enquiry Booking, Child, Notes, Nursery and Visit are created in redfish is automatically created in CRM
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify if the web page title actual "<expectedtitle>"
    And In home page verify if Enquiries and Enquiry in the main menu
    When Clicked on menu item "<MainMenuItem>" and submenu "<SubMenuItem>"
    Then Verify if the web page submenu title is "<expectedenqtitle>"
    When Parent First Name "<ParentFirstName>" Parent Second Name "<ParentSecondName>" Address "<Address>" Postcode "<Postcode>" MobileNumber "<MobileNumber>" Email id "<EmailId>"
    When The source is selected as "<Source>"
    When The First Child First Name "<FirstChildFirstName>" First Child Second Name "<SecondChildSecondName>" First Child DOB "<DOB>" Gender "<FirstChildGender>" Enrolment Start Date "<FirstEnrolmentStartDate>"
    When First child Booking Patten is "<BookingPatten>"
    When The Second Child First Name "<SecondChildFirstName>" Second Child Second Name "<SecondChildSecondName>" First Child DOB "<SecondChildDOB>" Gender "<SecondChildGender>" Enrolment Start Date "<SecondEnrolmentStartDate>"
    When Second Child Booking Patten is "<SecondBookingPatten>"
    Then Click on Add Enquiry
    Then Submit General Notes "<ParentName>"
    When Verify if user can add a visit with visit date "<VisitDate>" and visit time "<VisitTime>" with main comment "<ParentSecondName>"
    Then Logout from redfish and close browser

    Examples: 
      | UserName    | Password  | application | expectedtitle | MainMenuItem | SubMenuItem | expectedenqtitle | ParentFirstName | ParentSecondName | ParentName       | Address                 | Postcode | MobileNumber | EmailId                    | Source     | FirstChildFirstName | SecondChildSecondName | DOB        | FirstChildGender | FirstEnrolmentStartDate | FirstEnrolmentEndDate | BookingPatten | SecondChildFirstName | SecondChildSecondName | SecondChildDOB | SecondChildGender | SecondEnrolmentStartDate | SecondBookingPatten | EnquiryDetails  | Sibling | Relationship | ParentalResponsibility | PhotoPreference | TFCReference | LEAFEETReference | hrFundingCode | ChildProfileTitle | VisitDate  | VisitTime |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Jana            | Schoenfisch      | Jana Schoenfisch | 99-2190 St. Marys Road  | SO93 0LG |  07944582830 | jschoenfisch3f@webnode.com | BH Website | Thorn               | Schoenfisch           | 15/01/2018 | M                | 01/12/2020              | 12/12/2022            | All Days      | Obidiah              | Schoenfisch           | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000239 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Gery            | Jurries          | Gery Jurries     | 99-2191 St. Marys Road  | SO93 0LG |  07710994769 | gjurries3g@discuz.com      | BH Website | Mitchael            | Jurries               | 15/01/2018 | M                | 01/12/2020              | 12/12/2022            | All Days      | Howie                | Jurries               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000240 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Giustina        | Godsell          | Giustina Godsell | 99-2192 St. Marys Road  | SO94 0LG |  07859516650 | ggodsell3h@youtube.com     | BH Website | Dorrie              | Godsell               | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Gallagher            | Godsell               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000241 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Floyd           | Longhi           | Floyd Longhi     | 99-2193 St. Marys Road  | SO95 0LG |  07781482324 | flonghi3i@princeton.com    | BH Website | Linell              | Longhi                | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Hayden               | Longhi                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000242 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Hart            | Buie             | Hart Buie        | 99-2194 St. Marys Road  | SO96 0LG |  07539439782 | hbuie3j@a8.com             | BH Website | Celeste             | Buie                  | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Willdon              | Buie                  | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000243 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Mitch           | Cabble           | Mitch Cabble     | 99-21895 St. Marys Road | SO97 0LG |  07934077237 | mcabble3k@weebly.com       | BH Website | Elysia              | Cabble                | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Alister              | Cabble                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000244 | Child             | 21/01/2020 |      0930 |

  @CRMAddNP
  Scenario Outline: DataCreationInCRM_Verify if user is able to add a new Nursery Preference for an enquiry in CRM
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters RedfishCRM User Name "<UserName>" and Password "<Password>"
    Then Verify if the RedfishCRM web page title actual "<expectedtitle>"
    Then Verify if user able to search with parent email id "<ParentEmailID>" "<contactfilename>" "<ParentName>"
    Then Verify if user able to open the enquiry and verify the title as "<CRMEnquiryTitle>" screenshot in "<Enquiryfilename>"
    Then Verify if user is able to add "<Nursery>" in nursery preferred
    Then Logout from redfishCRM and close browser "<CRMlogoutfilename>"

    Examples: 
      | UserName                    | Password | application | expectedtitle                                             | ParentEmailID           | Postcode | ParentFirstName | ParentSecondName | ParentName         | EnquiryType | InvalidSearch | MobileNumber | contactfilename          | contactwithenqfilename      | CRMlogoutfilename              | CRMEnquiryTitle          | Enquiryfilename          | Nursery                                  | CRMVisitTitle      | Visitfilename          | FullNameFileName           | ParentEmailIDFileName                | Postcodefilename     | InvalidSearchFilename    | contactviewfilename    |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | amccomec0@telegraph.com | SO78 0LG | Alexine         | McCome           | Alexine McCome     | RedFish     | @#$           |  07879519460 | contactAlexineMcCome     | contactenqAlexineMcCome     | contactlogoutAlexineMcCome     | Enquiry: RedFish Enquiry | EnquiryAlexineMcCome     | Northwick Park Day Nursery and Preschool | Appointment: Visit | VisitAlexineMcCome     | FullNameAlexine McCome     | ParentEmailIDamccomec0@telegraph.com | PostcodefileSO78 0LG | InvalidsearchAlexine     | contactviewAlexine     |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | llarterc1@naver.com     | SO79 0LG | Luciano         | Larter           | Luciano Larter     | RedFish     | 14/10/2020    |  07953429162 | contactLucianoLarter     | contactenqLucianoLarter     | contactlogoutLucianoLarter     | Enquiry: RedFish Enquiry | EnquiryLucianoLarter     | Yellow Dot Ampfield                      | Appointment: Visit | VisitLucianoLarter     | FullNameLuciano Larter     | ParentEmailIDllarterc1@naver.com     | PostcodefileSO79 0LG | InvalidsearchLuciano     | contactviewLuciano     |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | emacmeanmac2@naver.com  | SO80 0LG | Editha          | MacMeanma        | Editha MacMeanma   | RedFish     | 901Editha     |  07279258624 | contactEdithaMacMeanma   | contactenqEdithaMacMeanma   | contactlogoutEdithaMacMeanma   | Enquiry: RedFish Enquiry | EnquiryEdithaMacMeanma   | Abbeymore Day Nursery and Preschool      | Appointment: Visit | VisitEdithaMacMeanma   | FullNameEditha MacMeanma   | ParentEmailIDemacmeanmac2@naver.com  | PostcodefileSO80 0LG | InvalidsearchEditha      | contactviewEditha      |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | jfeaverc3@google.com    | SO81 0LG | Julie           | Feaver           | Julie Feaver       | RedFish     | @#$           |  07504813697 | contactJulieFeaver       | contactenqJulieFeaver       | contactlogoutJulieFeaver       | Enquiry: RedFish Enquiry | EnquiryJulieFeaver       | Northwick Park Day Nursery and Preschool | Appointment: Visit | VisitJulieFeaver       | FullNameJulie Feaver       | ParentEmailIDjfeaverc3@google.com    | PostcodefileSO81 0LG | InvalidsearchJulie       | contactviewJulie       |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | zpardic4@sakura.com     | SO82 0LG | Zane            | Pardi            | Zane Pardi         | RedFish     | 14/10/2020    |  07553419964 | contactZanePardi         | contactenqZanePardi         | contactlogoutZanePardi         | Enquiry: RedFish Enquiry | EnquiryZanePardi         | Yellow Dot Ampfield                      | Appointment: Visit | VisitZanePardi         | FullNameZane Pardi         | ParentEmailIDzpardic4@sakura.com     | PostcodefileSO82 0LG | InvalidsearchZane        | contactviewZane        |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | sneilsonc5@go.com       | SO83 0LG | Sigrid          | Neilson          | Sigrid Neilson     | RedFish     | 901Sigrid     |  07469209115 | contactSigridNeilson     | contactenqSigridNeilson     | contactlogoutSigridNeilson     | Enquiry: RedFish Enquiry | EnquirySigridNeilson     | Abbeymore Day Nursery and Preschool      | Appointment: Visit | VisitSigridNeilson     | FullNameSigrid Neilson     | ParentEmailIDsneilsonc5@go.com       | PostcodefileSO83 0LG | InvalidsearchSigrid      | contactviewSigrid      |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | qdethloffc6@fc2.com     | SO84 0LG | Queenie         | Dethloff         | Queenie Dethloff   | RedFish     | @#$           |  07461504954 | contactQueenieDethloff   | contactenqQueenieDethloff   | contactlogoutQueenieDethloff   | Enquiry: RedFish Enquiry | EnquiryQueenieDethloff   | Northwick Park Day Nursery and Preschool | Appointment: Visit | VisitQueenieDethloff   | FullNameQueenie Dethloff   | ParentEmailIDqdethloffc6@fc2.com     | PostcodefileSO84 0LG | InvalidsearchQueenie     | contactviewQueenie     |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | jandinoc7@is.com        | SO85 0LG | Jacquenetta     | Andino           | Jacquenetta Andino | RedFish     | 14/10/2020    |  07288040166 | contactJacquenettaAndino | contactenqJacquenettaAndino | contactlogoutJacquenettaAndino | Enquiry: RedFish Enquiry | EnquiryJacquenettaAndino | Yellow Dot Ampfield                      | Appointment: Visit | VisitJacquenettaAndino | FullNameJacquenetta Andino | ParentEmailIDjandinoc7@is.com        | PostcodefileSO85 0LG | InvalidsearchJacquenetta | contactviewJacquenetta |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | cmcfiec8@vinaora.com    | SO86 0LG | Christie        | McFie            | Christie McFie     | RedFish     | 901Christie   |  07427861874 | contactChristieMcFie     | contactenqChristieMcFie     | contactlogoutChristieMcFie     | Enquiry: RedFish Enquiry | EnquiryChristieMcFie     | Abbeymore Day Nursery and Preschool      | Appointment: Visit | VisitChristieMcFie     | FullNameChristie McFie     | ParentEmailIDcmcfiec8@vinaora.com    | PostcodefileSO86 0LG | InvalidsearchChristie    | contactviewChristie    |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | slukovicc9@time.com     | SO87 0LG | Shell           | Lukovic          | Shell Lukovic      | RedFish     | 14/10/2020    |  07699081109 | contactShellLukovic      | contactenqShellLukovic      | contactlogoutShellLukovic      | Enquiry: RedFish Enquiry | EnquiryShellLukovic      | Northwick Park Day Nursery and Preschool | Appointment: Visit | VisitShellLukovic      | FullNameShell Lukovic      | ParentEmailIDslukovicc9@time.com     | PostcodefileSO87 0LG | InvalidsearchShell       | contactviewShell       |
      | 99160101@brighthorizons.com | Sam19You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | cdevonsca@hc360.com     | SO88 0LG | Case            | Devons           | Case Devons        | RedFish     | 901Case       |  07786200301 | contactCaseDevons        | contactenqCaseDevons        | contactlogoutCaseDevons        | Enquiry: RedFish Enquiry | EnquiryCaseDevons        | Yellow Dot Ampfield                      | Appointment: Visit | VisitCaseDevons        | FullNameCase Devons        | ParentEmailIDcdevonsca@hc360.com     | PostcodefileSO88 0LG |                          | contactviewCase        |

  @SmokeRegressionTC1_3 @Register
  Scenario Outline: Verify if user is able to register one child
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify if the web page title actual "<expectedtitle>"
    Then Verify search functionality with only Parent Name "<EmailId>" in search page
    Then Verify Enquiry search functionality with only Parent Name "<EmailId>" in search page
    When Clicked on register First child with sibling with "<Sibling>"
    When Selecting the Relationship status as "<Relationship>" and Parental Parental Responsibility as "<ParentalResponsibility>"
    When Selecting the PhotoPreference as "<PhotoPreference>"
    When The TFC Reference "<TFCReference>" and LEAFEETReference "<LEAFEETReference>" and hrFundingCode "<hrFundingCode>"
    When The Enrolment Leave date is "<FirstEnrolmentEndDate>"
    Then Verify if the child is registered "<ChildProfileTitle>"
    Then Logout from redfish and close browser

    Examples: 
      | UserName    | Password  | application | expectedtitle | MainMenuItem | SubMenuItem | expectedenqtitle | ParentFirstName | ParentSecondName | ParentName       | Address                 | Postcode | MobileNumber | EmailId                    | Source     | FirstChildFirstName | SecondChildSecondName | DOB        | FirstChildGender | FirstEnrolmentStartDate | FirstEnrolmentEndDate | BookingPatten | SecondChildFirstName | SecondChildSecondName | SecondChildDOB | SecondChildGender | SecondEnrolmentStartDate | SecondBookingPatten | EnquiryDetails  | Sibling | Relationship | ParentalResponsibility | PhotoPreference | TFCReference | LEAFEETReference | hrFundingCode | ChildProfileTitle | VisitDate  | VisitTime |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Jana            | Schoenfisch      | Jana Schoenfisch | 99-2190 St. Marys Road  | SO93 0LG |  07944582830 | jschoenfisch3f@webnode.com | BH Website | Thorn               | Schoenfisch           | 15/01/2018 | M                | 01/12/2020              | 12/12/2022            | All Days      | Obidiah              | Schoenfisch           | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000239 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Gery            | Jurries          | Gery Jurries     | 99-2191 St. Marys Road  | SO93 0LG |  07710994769 | gjurries3g@discuz.com      | BH Website | Mitchael            | Jurries               | 15/01/2018 | M                | 01/12/2020              | 12/12/2022            | All Days      | Howie                | Jurries               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000240 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Giustina        | Godsell          | Giustina Godsell | 99-2192 St. Marys Road  | SO94 0LG |  07859516650 | ggodsell3h@youtube.com     | BH Website | Dorrie              | Godsell               | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Gallagher            | Godsell               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000241 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Floyd           | Longhi           | Floyd Longhi     | 99-2193 St. Marys Road  | SO95 0LG |  07781482324 | flonghi3i@princeton.com    | BH Website | Linell              | Longhi                | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Hayden               | Longhi                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000242 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Hart            | Buie             | Hart Buie        | 99-2194 St. Marys Road  | SO96 0LG |  07539439782 | hbuie3j@a8.com             | BH Website | Celeste             | Buie                  | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Willdon              | Buie                  | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000243 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Mitch           | Cabble           | Mitch Cabble     | 99-21895 St. Marys Road | SO97 0LG |  07934077237 | mcabble3k@weebly.com       | BH Website | Elysia              | Cabble                | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Alister              | Cabble                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000244 | Child             | 21/01/2020 |      0930 |

  @Register @2ndRegister @Register
  Scenario Outline: Verify if user is able to register the 2nd Child
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify if the web page title actual "<expectedtitle>"
    Then Verify search functionality with only Parent Name "<EmailId>" in search page
    Then Verify Enquiry search functionality with only Parent Name "<EmailId>" in search page
    When Clicked on register Second child with sibling "<Sibling>"
    When Selecting the Relationship status as "<Relationship>" and Parental Parental Responsibility as "<ParentalResponsibility>"
    When Selecting the PhotoPreference as "<PhotoPreference>"
    When The TFC Reference "<TFCReference>" and LEAFEETReference "<LEAFEETReference>" and hrFundingCode "<hrFundingCode>"
    When The Enrolment Leave date is "<FirstEnrolmentEndDate>"
    Then Verify if the child is registered "<ChildProfileTitle>"
    Then Logout from redfish and close browser

    Examples: 
      | UserName    | Password  | application | expectedtitle | MainMenuItem | SubMenuItem | expectedenqtitle | ParentFirstName | ParentSecondName | ParentName       | Address                 | Postcode | MobileNumber | EmailId                    | Source     | FirstChildFirstName | SecondChildSecondName | DOB        | FirstChildGender | FirstEnrolmentStartDate | FirstEnrolmentEndDate | BookingPatten | SecondChildFirstName | SecondChildSecondName | SecondChildDOB | SecondChildGender | SecondEnrolmentStartDate | SecondBookingPatten | EnquiryDetails  | Sibling | Relationship | ParentalResponsibility | PhotoPreference | TFCReference | LEAFEETReference | hrFundingCode | ChildProfileTitle | VisitDate  | VisitTime |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Jana            | Schoenfisch      | Jana Schoenfisch | 99-2190 St. Marys Road  | SO93 0LG |  07944582830 | jschoenfisch3f@webnode.com | BH Website | Thorn               | Schoenfisch           | 15/01/2018 | M                | 01/12/2020              | 12/12/2022            | All Days      | Obidiah              | Schoenfisch           | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000239 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Gery            | Jurries          | Gery Jurries     | 99-2191 St. Marys Road  | SO93 0LG |  07710994769 | gjurries3g@discuz.com      | BH Website | Mitchael            | Jurries               | 15/01/2018 | M                | 01/12/2020              | 12/12/2022            | All Days      | Howie                | Jurries               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000240 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Giustina        | Godsell          | Giustina Godsell | 99-2192 St. Marys Road  | SO94 0LG |  07859516650 | ggodsell3h@youtube.com     | BH Website | Dorrie              | Godsell               | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Gallagher            | Godsell               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000241 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Floyd           | Longhi           | Floyd Longhi     | 99-2193 St. Marys Road  | SO95 0LG |  07781482324 | flonghi3i@princeton.com    | BH Website | Linell              | Longhi                | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Hayden               | Longhi                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000242 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Hart            | Buie             | Hart Buie        | 99-2194 St. Marys Road  | SO96 0LG |  07539439782 | hbuie3j@a8.com             | BH Website | Celeste             | Buie                  | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Willdon              | Buie                  | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000243 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Mitch           | Cabble           | Mitch Cabble     | 99-21895 St. Marys Road | SO97 0LG |  07934077237 | mcabble3k@weebly.com       | BH Website | Elysia              | Cabble                | 15/01/2018 | F                | 01/12/2020              | 12/12/2022            | All Days      | Alister              | Cabble                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000244 | Child             | 21/01/2020 |      0930 |

  @SmokeRegressionTC1_2
  Scenario Outline: DataVerificationInCRM_Verify if redfish Enquiry Booking, Child, Notes, Nursery and Visit are created in redfish is automatically created in CRM
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters RedfishCRM User Name "<UserName>" and Password "<Password>"
    Then Verify if the RedfishCRM web page title actual "<expectedtitle>"
    Then Verify if user able to search with parent email id "<ParentEmailID>" "<contactfilename>" "<ParentName>"
    Then Verify if Enquiry is created by taking the screen shot of the enquiry table "<contactwithenqfilename>"
    Then Verify if user able to open the enquiry and verify the title as "<CRMEnquiryTitle>" screenshot in "<Enquiryfilename>"
    Then Verify if user able to open the visit and verify the title as "<CRMVisitTitle>" screenshot in "<Visitfilename>"
    Then Logout from redfishCRM and close browser "<CRMlogoutfilename>"

    Examples: 
      | UserName                    | Password | application | expectedtitle                                             | ParentEmailID            | Postcode | ParentFirstName | ParentSecondName | ParentName       | EnquiryType | InvalidSearch | MobileNumber | contactfilename        | contactwithenqfilename    | CRMlogoutfilename            | CRMEnquiryTitle          | Enquiryfilename        | CRMVisitTitle      | Visitfilename        | FullNameFileName         | ParentEmailIDFileName                 | Postcodefilename     | InvalidSearchFilename | contactviewfilename |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | lashfoldgl@netscape.com  | SO38 0LG | Lezlie          | Tythacott        | Lezlie Tythacott | RedFish     | @#$           |  07214596965 | contactLezlieTythacott | contactenqLezlieTythacott | contactlogoutLezlieTythacott | Enquiry: RedFish Enquiry | EnquiryLezlieTythacott | Appointment: Visit | VisitLezlieTythacott | FullNameLezlie Tythacott | ParentEmailIDlashfoldgl@netscape.com  | PostcodefileSO38 0LG | InvalidsearchLezlie   | contactviewLezlie   |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | parentgm@theatlantic.com | SO39 0LG | Patin           | Blouet           | Patin Blouet     | RedFish     | 14/10/2020    |  07374096556 | contactPatinBlouet     | contactenqPatinBlouet     | contactlogoutPatinBlouet     | Enquiry: RedFish Enquiry | EnquiryPatinBlouet     | Appointment: Visit | VisitPatinBlouet     | FullNamePatin Blouet     | ParentEmailIDparentgm@theatlantic.com | PostcodefileSO39 0LG | InvalidsearchPatin    | contactviewPatin    |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | lgwylltgn@ebay.com       | SO40 0LG | Laural          | Langfield        | Laural Langfield | RedFish     | 901Laural     |  07727152892 | contactLauralLangfield | contactenqLauralLangfield | contactlogoutLauralLangfield | Enquiry: RedFish Enquiry | EnquiryLauralLangfield | Appointment: Visit | VisitLauralLangfield | FullNameLaural Langfield | ParentEmailIDlgwylltgn@ebay.com       | PostcodefileSO40 0LG | InvalidsearchLaural   | contactviewLaural   |

  @Register2Children
  Scenario Outline: DataVerificationInCRM_Verify if redfish Enquiry Booking, Child, Notes, Nursery and Visit are created in redfish is automatically created in CRM
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters RedfishCRM User Name "<UserName>" and Password "<Password>"
    Then Verify if the RedfishCRM web page title actual "<expectedtitle>"
    Then Verify if user able to search with parent email id "<ParentEmailID>" "<contactfilename>" "<ParentName>"
    Then Verify if Enquiry is created by taking the screen shot of the enquiry table "<contactwithenqfilename>"
    Then Verify if user able to open the enquiry and verify the title as "<CRMEnquiryTitle>" screenshot in "<Enquiryfilename>"
    Then Verify if user able to open the visit and verify the title as "<CRMVisitTitle>" screenshot in "<Visitfilename>"
    Then Logout from redfishCRM and close browser "<CRMlogoutfilename>"

    Examples: 
      | UserName                    | Password | application | expectedtitle                                             | ParentEmailID            | Postcode | ParentFirstName | ParentSecondName | ParentName       | EnquiryType | InvalidSearch | MobileNumber | contactfilename        | contactwithenqfilename    | CRMlogoutfilename            | CRMEnquiryTitle          | Enquiryfilename        | CRMVisitTitle      | Visitfilename        | FullNameFileName         | ParentEmailIDFileName                 | Postcodefilename     | InvalidSearchFilename | contactviewfilename |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | lashfoldgl@netscape.com  | SO38 0LG | Lezlie          | Tythacott        | Lezlie Tythacott | RedFish     | @#$           |  07214596965 | contactLezlieTythacott | contactenqLezlieTythacott | contactlogoutLezlieTythacott | Enquiry: RedFish Enquiry | EnquiryLezlieTythacott | Appointment: Visit | VisitLezlieTythacott | FullNameLezlie Tythacott | ParentEmailIDlashfoldgl@netscape.com  | PostcodefileSO38 0LG | InvalidsearchLezlie   | contactviewLezlie   |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | parentgm@theatlantic.com | SO39 0LG | Patin           | Blouet           | Patin Blouet     | RedFish     | 14/10/2020    |  07374096556 | contactPatinBlouet     | contactenqPatinBlouet     | contactlogoutPatinBlouet     | Enquiry: RedFish Enquiry | EnquiryPatinBlouet     | Appointment: Visit | VisitPatinBlouet     | FullNamePatin Blouet     | ParentEmailIDparentgm@theatlantic.com | PostcodefileSO39 0LG | InvalidsearchPatin    | contactviewPatin    |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | lgwylltgn@ebay.com       | SO40 0LG | Laural          | Langfield        | Laural Langfield | RedFish     | 901Laural     |  07727152892 | contactLauralLangfield | contactenqLauralLangfield | contactlogoutLauralLangfield | Enquiry: RedFish Enquiry | EnquiryLauralLangfield | Appointment: Visit | VisitLauralLangfield | FullNameLaural Langfield | ParentEmailIDlgwylltgn@ebay.com       | PostcodefileSO40 0LG | InvalidsearchLaural   | contactviewLaural   |

  @CRMPhoneEnquiry
  Scenario Outline: DataCreationInCRM_Verify if user is able to create a phone enquiry from CRM
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters RedfishCRM User Name "<UserName>" and Password "<Password>"
    Then Verify if the RedfishCRM web page title actual "<expectedtitle>"
    Then Verify if user is able to click on new contact and get the actual title "<expnewcontacttitle>"
    Then Type Parent First Name "<ParentFirstName>" Parent Second Name "<ParentSecondName>" Address "<Address>" Postcode "<Postcode>" MobileNumber "<MobileNumber>" Email id "<ParentEmailID>" Relationship Type "<relationshipType>"
    Then Take screen shot in file name "<NewContactfilename>"
    Then Logout from redfishCRM and close browser "<CRMlogoutfilename>"

    Examples: 
      | UserName                    | Password | application | expectedtitle                                             | expnewcontacttitle   | ParentFirstName | ParentSecondName | ParentName     | CRMlogoutfilename          | ParentEmailID              | Postcode | MobileNumber | NewContactfilename      | relationshipType |
      | 99160101@brighthorizons.com | Sam18You | UATCRMUrl   | Contacts Active Parents/Guardian - Microsoft Dynamics 365 | Contact: New Contact | Krista          | Moffett          | Krista Moffett | contactlogoutKristaMoffett | kmoffettel@independent.com | SO45 0LG |  07803935159 | NewContactKristaMoffett | Parent           |

  @SingleChildEnquiry @RegisterSingleChild
  Scenario Outline: DataSingleChidlCreationInRedfish_Verify if redfish Enquiry Booking, Child, Notes, Nursery and Visit are created in redfish is automatically created in CRM
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify if the web page title actual "<expectedtitle>"
    And In home page verify if Enquiries and Enquiry in the main menu
    When Clicked on menu item "<MainMenuItem>" and submenu "<SubMenuItem>"
    Then Verify if the web page submenu title is "<expectedenqtitle>"
    When Parent First Name "<ParentFirstName>" Parent Second Name "<ParentSecondName>" Address "<Address>" Postcode "<Postcode>" MobileNumber "<MobileNumber>" Email id "<EmailId>"
    When The source is selected as "<Source>"
    When The First Child First Name "<FirstChildFirstName>" First Child Second Name "<SecondChildSecondName>" First Child DOB "<DOB>" Gender "<FirstChildGender>" Enrolment Start Date "<FirstEnrolmentStartDate>"
    When First child Booking Patten is "<BookingPatten>"
    Then Click on Add Enquiry
    Then Submit General Notes "<ParentName>"
    Then Logout from redfish and close browser

    Examples: 
      | UserName    | Password  | application | expectedtitle | MainMenuItem | SubMenuItem | expectedenqtitle | ParentFirstName | ParentSecondName | ParentName        | Address                  | Postcode | MobileNumber | EmailId                          | Source     | FirstChildFirstName | SecondChildSecondName | DOB        | FirstChildGender | FirstEnrolmentStartDate | FirstEnrolmentEndDate | BookingPatten                     | SecondChildFirstName | SecondChildSecondName | SecondChildDOB | SecondChildGender | SecondEnrolmentStartDate | SecondBookingPatten | EnquiryDetails  | Sibling | Relationship | ParentalResponsibility | PhotoPreference | TFCReference | LEAFEETReference | hrFundingCode | ChildProfileTitle | VisitDate  | VisitTime |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Layne           | Tuohy            | Layne Tuohy       | 4 Arkansas Parkway       | SO01 0LG |  07390646579 | ltuohy0@ox.com                   | BH Website | Lesley              | Tuohy                 | 15/01/2019 | M                | 04/01/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW FAM FPM   | Obidiah              | Tuohy                 | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000001 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Jeri            | Hanster          | Jeri Hanster      | 6283 Browning Place      | SO02 0LG |  07172703855 | jhanster1@cisco.com              | BH Website | Leonidas            | Hanster               | 15/01/2019 | M                | 05/01/2021              | 12/12/2022            | All Days                          | Howie                | Hanster               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000002 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Elisabet        | Casetta          | Elisabet Casetta  | 2365 Quincy Place        | SO03 0LG |  07362662900 | ecasetta2@marketwatch.com        | BH Website | Elayne              | Casetta               | 15/01/2019 | F                | 05/01/2021              | 12/12/2022            | AMM AMT PMT AMW PMW THAM THPM     | Gallagher            | Casetta               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000003 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Jillane         | Bransden         | Jillane Bransden  | 5 Farmco Place           | SO04 0LG |  07808014332 | jbransden3@netlog.com            | BH Website | Worthy              | Bransden              | 15/01/2019 | M                | 06/01/2021              | 12/12/2022            | AMM PMM AMT PMT FAM FPM           | Hayden               | Bransden              | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000004 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Livvie          | Patching         | Livvie Patching   | 85 Main Lane             | SO05 0LG |  07922925637 | lpatching4@jigsy.com             | BH Website | Jacquelynn          | Patching              | 15/01/2019 | F                | 01/02/2021              | 12/12/2022            | AMM AMT AMW AMTH AMF PMM          | Willdon              | Patching              | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000005 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Milly           | Overton          | Milly Overton     | 21421 Welch Lane         | SO06 0LG |  07188392873 | moverton5@hhs.com                | BH Website | Jodi                | Overton               | 15/01/2019 | M                | 28/01/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW           | Alister              | Overton               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000006 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Tamra           | Carhart          | Tamra Carhart     | 44072 Scofield Terrace   | SO07 0LG |  07962889805 | tcarhart6@nasa.com               | BH Website | Karlee              | Carhart               | 15/01/2019 | F                | 04/01/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW FAM FPM   | Obidiah              | Carhart               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000007 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Gaylor          | McFall           | Gaylor McFall     | 59 Tomscot Circle        | SO08 0LG |  07905123531 | gmcfall7@psu.com                 | BH Website | Chrissy             | McFall                | 15/01/2019 | F                | 05/01/2021              | 12/12/2022            | AMT AMW PMW THAM THPM             | Howie                | McFall                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000008 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Allx            | Schultz          | Allx Schultz      | 28 Dorton Trail          | SO09 0LG |  07511498065 | aschultz8@elegantthemes.com      | BH Website | Mahalia             | Schultz               | 15/01/2019 | F                | 05/01/2021              | 12/12/2022            | All AM                            | Gallagher            | Schultz               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000009 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Marylin         | Biskupiak        | Marylin Biskupiak | 303 Grover Park          | SO10 0LG |  07209563383 | mbiskupiak9@senate.com           | BH Website | Napoleon            | Biskupiak             | 15/01/2019 | M                | 06/01/2021              | 12/12/2022            | AMT PMT AMW                       | Hayden               | Biskupiak             | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000010 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Kaela           | McDuffy          | Kaela McDuffy     | 86183 Katie Center       | SO11 0LG |  07152660119 | kmcduffya@yelp.com               | BH Website | Holli               | McDuffy               | 15/01/2019 | F                | 01/02/2021              | 12/12/2022            | AMT THAM                          | Willdon              | McDuffy               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000011 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Mikel           | Crowden          | Mikel Crowden     | 4958 Northview Road      | SO12 0LG |  07860592754 | mcrowdenb@nationalgeographic.com | BH Website | Elie                | Crowden               | 15/01/2019 | F                | 28/01/2021              | 12/12/2022            | AMT PMT THAM THPM                 | Alister              | Crowden               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000012 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Courtney        | Benardet         | Courtney Benardet | 75 Derek Point           | SO13 0LG |  07121136047 | cbenardetc@list-manage.com       | BH Website | Raffaello           | Benardet              | 15/01/2019 | M                | 04/01/2021              | 12/12/2022            | AMM PMM TAM TPM FAM FPM           | Obidiah              | Benardet              | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Bentley         | Killner          | Bentley Killner   | 29015 Meadow Ridge Plaza | SO14 0LG |  07219218262 | bkillnerd@mozilla.com            | BH Website | Evered              | Killner               | 15/01/2019 | M                | 05/01/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW           | Howie                | Killner               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000014 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Verge           | Thomtson         | Verge Thomtson    | 3 Thierer Point          | SO15 0LG |  07015102756 | vthomtsone@techcrunch.com        | BH Website | Kristofor           | Thomtson              | 15/01/2019 | M                | 05/01/2021              | 12/12/2022            | AMM PMM THAM                      | Gallagher            | Thomtson              | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000015 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Dorian          | Tallach          | Dorian Tallach    | 379 Manufacturers Avenue | SO16 0LG |  07494879207 | dtallachf@canalblog.com          | BH Website | Liane               | Tallach               | 15/01/2019 | F                | 06/01/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW AMTH PMTH | Hayden               | Tallach               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000016 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Wallas          | Poulsom          | Wallas Poulsom    | 65 Warbler Avenue        | SO17 0LG |  07950911645 | wpoulsomg@samsung.com            | BH Website | Dermot              | Poulsom               | 15/01/2019 | M                | 01/02/2021              | 12/12/2022            | AMM PMM AMTH PMTH                 | Willdon              | Poulsom               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000017 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Blanche         | Branwhite        | Blanche Branwhite | 0205 Oriole Point        | SO18 0LG |  07140990561 | bbranwhiteh@free.com             | BH Website | Conrade             | Branwhite             | 15/01/2019 | M                | 28/01/2021              | 12/12/2022            | AMM PMM AMT PMT                   | Alister              | Branwhite             | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000018 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Deeyn           | Darnbrook        | Deeyn Darnbrook   | 98408 Trailsway Point    | SO19 0LG |  07369755304 | ddarnbrooki@hubpages.com         | BH Website | Gwennie             | Darnbrook             | 15/01/2019 | F                | 05/01/2021              | 12/12/2022            | All Days                          | Gallagher            | Darnbrook             | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000019 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Cthrine         | Graben           | Cthrine Graben    | 632 Eastwood Parkway     | SO20 0LG |  07106597794 | cgrabenj@npr.com                 | BH Website | Aldric              | Graben                | 15/01/2019 | M                | 06/01/2021              | 12/12/2022            | All Days                          | Hayden               | Graben                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000020 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Janith          | Streets          | Janith Streets    | 20951 Spohn Crossing     | SO21 0LG |  07344089914 | jstreetsk@guardian.com           | BH Website | Eliza               | Streets               | 15/01/2019 | F                | 01/02/2021              | 12/12/2022            | AMT PMT AMTH PMTH                 | Willdon              | Streets               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000021 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Meryl           | Larroway         | Meryl Larroway    | 229 Riverside Terrace    | SO22 0LG |  07125977493 | mlarrowayl@nyu.com               | BH Website | Melissa             | Larroway              | 15/01/2019 | F                | 28/01/2021              | 12/12/2022            | AMM PMM AMT PMT                   | Alister              | Larroway              | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000022 | Child             | 21/01/2020 |      0930 |

  @RegisterSingleChild
  Scenario Outline: Verify if user is able to register one child
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify if the web page title actual "<expectedtitle>"
    Then Verify search functionality with only Parent Name "<EmailId>" in search page
    Then Verify Enquiry search functionality with only Parent Name "<EmailId>" in search page
    When Clicked on register First child with sibling with "<Sibling>"
    When Selecting the Relationship status as "<Relationship>" and Parental Parental Responsibility as "<ParentalResponsibility>"
    When Selecting the PhotoPreference as "<PhotoPreference>"
    When The TFC Reference "<TFCReference>" and LEAFEETReference "<LEAFEETReference>" and hrFundingCode "<hrFundingCode>"
    When The Enrolment Leave date is "<FirstEnrolmentEndDate>"
    Then Verify if the child is registered "<ChildProfileTitle>"
    Then Logout from redfish and close browser

    Examples: 
      | UserName    | Password  | application | expectedtitle | MainMenuItem | SubMenuItem | expectedenqtitle | ParentFirstName | ParentSecondName | ParentName        | Address                  | Postcode | MobileNumber | EmailId                          | Source     | FirstChildFirstName | SecondChildSecondName | DOB        | FirstChildGender | FirstEnrolmentStartDate | FirstEnrolmentEndDate | BookingPatten                     | SecondChildFirstName | SecondChildSecondName | SecondChildDOB | SecondChildGender | SecondEnrolmentStartDate | SecondBookingPatten | EnquiryDetails  | Sibling | Relationship | ParentalResponsibility | PhotoPreference | TFCReference | LEAFEETReference | hrFundingCode | ChildProfileTitle | VisitDate  | VisitTime |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Layne           | Tuohy            | Layne Tuohy       | 4 Arkansas Parkway       | SO01 0LG |  07390646579 | ltuohy0@ox.com                   | BH Website | Lesley              | Tuohy                 | 15/01/2019 | M                | 04/01/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW FAM FPM   | Obidiah              | Tuohy                 | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000001 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Jeri            | Hanster          | Jeri Hanster      | 6283 Browning Place      | SO02 0LG |  07172703855 | jhanster1@cisco.com              | BH Website | Leonidas            | Hanster               | 15/01/2019 | M                | 05/01/2021              | 12/12/2022            | All Days                          | Howie                | Hanster               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000002 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Elisabet        | Casetta          | Elisabet Casetta  | 2365 Quincy Place        | SO03 0LG |  07362662900 | ecasetta2@marketwatch.com        | BH Website | Elayne              | Casetta               | 15/01/2019 | F                | 05/01/2021              | 12/12/2022            | AMM AMT PMT AMW PMW THAM THPM     | Gallagher            | Casetta               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000003 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Jillane         | Bransden         | Jillane Bransden  | 5 Farmco Place           | SO04 0LG |  07808014332 | jbransden3@netlog.com            | BH Website | Worthy              | Bransden              | 15/01/2019 | M                | 06/01/2021              | 12/12/2022            | AMM PMM AMT PMT FAM FPM           | Hayden               | Bransden              | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000004 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Livvie          | Patching         | Livvie Patching   | 85 Main Lane             | SO05 0LG |  07922925637 | lpatching4@jigsy.com             | BH Website | Jacquelynn          | Patching              | 15/01/2019 | F                | 01/02/2021              | 12/12/2022            | AMM AMT AMW AMTH AMF PMM          | Willdon              | Patching              | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000005 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Milly           | Overton          | Milly Overton     | 21421 Welch Lane         | SO06 0LG |  07188392873 | moverton5@hhs.com                | BH Website | Jodi                | Overton               | 15/01/2019 | M                | 28/01/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW           | Alister              | Overton               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000006 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Tamra           | Carhart          | Tamra Carhart     | 44072 Scofield Terrace   | SO07 0LG |  07962889805 | tcarhart6@nasa.com               | BH Website | Karlee              | Carhart               | 15/01/2019 | F                | 04/01/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW FAM FPM   | Obidiah              | Carhart               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000007 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Gaylor          | McFall           | Gaylor McFall     | 59 Tomscot Circle        | SO08 0LG |  07905123531 | gmcfall7@psu.com                 | BH Website | Chrissy             | McFall                | 15/01/2019 | F                | 05/01/2021              | 12/12/2022            | AMT AMW PMW THAM THPM             | Howie                | McFall                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000008 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Allx            | Schultz          | Allx Schultz      | 28 Dorton Trail          | SO09 0LG |  07511498065 | aschultz8@elegantthemes.com      | BH Website | Mahalia             | Schultz               | 15/01/2019 | F                | 05/01/2021              | 12/12/2022            | All AM                            | Gallagher            | Schultz               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000009 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Marylin         | Biskupiak        | Marylin Biskupiak | 303 Grover Park          | SO10 0LG |  07209563383 | mbiskupiak9@senate.com           | BH Website | Napoleon            | Biskupiak             | 15/01/2019 | M                | 06/01/2021              | 12/12/2022            | AMT PMT AMW                       | Hayden               | Biskupiak             | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000010 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Kaela           | McDuffy          | Kaela McDuffy     | 86183 Katie Center       | SO11 0LG |  07152660119 | kmcduffya@yelp.com               | BH Website | Holli               | McDuffy               | 15/01/2019 | F                | 01/02/2021              | 12/12/2022            | AMT THAM                          | Willdon              | McDuffy               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000011 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Mikel           | Crowden          | Mikel Crowden     | 4958 Northview Road      | SO12 0LG |  07860592754 | mcrowdenb@nationalgeographic.com | BH Website | Elie                | Crowden               | 15/01/2019 | F                | 28/01/2021              | 12/12/2022            | AMT PMT THAM THPM                 | Alister              | Crowden               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000012 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Courtney        | Benardet         | Courtney Benardet | 75 Derek Point           | SO13 0LG |  07121136047 | cbenardetc@list-manage.com       | BH Website | Raffaello           | Benardet              | 15/01/2019 | M                | 04/01/2021              | 12/12/2022            | AMM PMM TAM TPM FAM FPM           | Obidiah              | Benardet              | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Bentley         | Killner          | Bentley Killner   | 29015 Meadow Ridge Plaza | SO14 0LG |  07219218262 | bkillnerd@mozilla.com            | BH Website | Evered              | Killner               | 15/01/2019 | M                | 05/01/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW           | Howie                | Killner               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000014 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Verge           | Thomtson         | Verge Thomtson    | 3 Thierer Point          | SO15 0LG |  07015102756 | vthomtsone@techcrunch.com        | BH Website | Kristofor           | Thomtson              | 15/01/2019 | M                | 05/01/2021              | 12/12/2022            | AMM PMM THAM                      | Gallagher            | Thomtson              | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000015 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Dorian          | Tallach          | Dorian Tallach    | 379 Manufacturers Avenue | SO16 0LG |  07494879207 | dtallachf@canalblog.com          | BH Website | Liane               | Tallach               | 15/01/2019 | F                | 06/01/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW AMTH PMTH | Hayden               | Tallach               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000016 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Wallas          | Poulsom          | Wallas Poulsom    | 65 Warbler Avenue        | SO17 0LG |  07950911645 | wpoulsomg@samsung.com            | BH Website | Dermot              | Poulsom               | 15/01/2019 | M                | 01/02/2021              | 12/12/2022            | AMM PMM AMTH PMTH                 | Willdon              | Poulsom               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000017 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Blanche         | Branwhite        | Blanche Branwhite | 0205 Oriole Point        | SO18 0LG |  07140990561 | bbranwhiteh@free.com             | BH Website | Conrade             | Branwhite             | 15/01/2019 | M                | 28/01/2021              | 12/12/2022            | AMM PMM AMT PMT                   | Alister              | Branwhite             | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000018 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Deeyn           | Darnbrook        | Deeyn Darnbrook   | 98408 Trailsway Point    | SO19 0LG |  07369755304 | ddarnbrooki@hubpages.com         | BH Website | Gwennie             | Darnbrook             | 15/01/2019 | F                | 05/01/2021              | 12/12/2022            | All Days                          | Gallagher            | Darnbrook             | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000019 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Cthrine         | Graben           | Cthrine Graben    | 632 Eastwood Parkway     | SO20 0LG |  07106597794 | cgrabenj@npr.com                 | BH Website | Aldric              | Graben                | 15/01/2019 | M                | 06/01/2021              | 12/12/2022            | All Days                          | Hayden               | Graben                | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000020 | Child             | 21/01/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Janith          | Streets          | Janith Streets    | 20951 Spohn Crossing     | SO21 0LG |  07344089914 | jstreetsk@guardian.com           | BH Website | Eliza               | Streets               | 15/01/2019 | F                | 01/02/2021              | 12/12/2022            | AMT PMT AMTH PMTH                 | Willdon              | Streets               | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000021 | Child             | 21/01/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Meryl           | Larroway         | Meryl Larroway    | 229 Riverside Terrace    | SO22 0LG |  07125977493 | mlarrowayl@nyu.com               | BH Website | Melissa             | Larroway              | 15/01/2019 | F                | 28/01/2021              | 12/12/2022            | AMM PMM AMT PMT                   | Alister              | Larroway              | 15/01/2018     | M                 | 12/12/2022               | All Days            | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000022 | Child             | 21/01/2020 |      0930 |
