Feature: 03.1 Enquiry Management

  @SingleChildEnquiry @Bug-2591
  Scenario Outline: DataSingleChidlCreationInRedfish_Verify if redfish Enquiry Booking, Child, Notes, Nursery and Visit are created in redfish is automatically created in CRM
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify if the web page title actual "<expectedtitle>"
    And In home page verify if Enquiries and Enquiry in the main menu
    When Clicked on menu item "<MainMenuItem>" and submenu "<SubMenuItem>"
    Then Verify if the web page submenu title is "<expectedenqtitle>"
    When Parent First Name "<ParentFirstName>" Parent Second Name "<ParentSecondName>" Address "<Address>" Postcode "<Postcode>" MobileNumber "<MobileNumber>" Email id "<EmailId>"
    When The source is selected as "<Source>"
    When The First Child First Name "<FirstChildFirstName>" First Child Second Name "<SecondChildSecondName>" First Child DOB "<DOB>" Gender "<FirstChildGender>" Enrolment Start Date "<FirstEnrolmentStartDate>"
    When First child Booking Patten is "<BookingPatten>"
    Then Click on Add Enquiry
    Then Submit General Notes "<ParentName>"
    Then Logout from redfish and close browser

    Examples: 
      | UserName    | Password  | application | expectedtitle | MainMenuItem | SubMenuItem | expectedenqtitle | ParentFirstName | ParentSecondName | ParentName     | Address              | Postcode | MobileNumber | EmailId                  | Source     | FirstChildFirstName | SecondChildSecondName | DOB        | FirstChildGender | FirstEnrolmentStartDate | FirstEnrolmentEndDate | BookingPatten                   | SecondChildFirstName | SecondChildSecondName | SecondChildDOB | SecondChildGender | SecondEnrolmentStartDate | SecondBookingPatten             | EnquiryDetails  | Sibling | Relationship | ParentalResponsibility | PhotoPreference | TFCReference | LEAFEETReference | hrFundingCode | ChildProfileTitle | VisitDate  | VisitTime |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Nessi           | Caberas          | Nessi Caberas  | 977 Hanson Avenue    | SO60 0LG |  07641570156 | ncaberasby@bloglines.com | BH Website | Annabel             | Caberas               | 27/04/2019 | M                | 19/04/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW FAM FPM | Nara                 | Caberas               | 15/01/2020     | F                 | 01/04/2021               | AMM PMM AMT PMT AMW PMW FAM FPM | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Liane           | Aleshkov         | Liane Aleshkov | 392 Sutherland Trail | SO61 0LG |  07169091544 | laleshkovbz@slashdot.com | BH Website | Aloysius            | Aleshkov              | 28/09/2019 | M                | 01/04/2021              | 12/12/2022            | All Days                        | Emelyne              | Aleshkov              | 15/01/2020     | F                 | 01/04/2021               | AMM PMM AMT PMT AMW PMW FAM FPM | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Bron            | Rumens           | Bron Rumens    | 63699 Erie Park      | SO62 0LG |  07680691347 | brumensc0@bloomberg.com  | BH Website | Inger               | Rumens                | 29/02/2018 | F                | 01/04/2021              | 12/12/2022            | AMM AMT PMT AMW PMW THAM THPM   | Ali                  | Rumens                | 15/01/2020     | F                 | 01/04/2021               | AMM AMT PMT AMW PMW THAM THPM   | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |

  @TwoChildrenEnquiry
  Scenario Outline: DataCreationInRedfish_Verify if redfish Enquiry Booking, Child, Notes, Nursery and Visit are created in redfish is automatically created in CRM
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify if the web page title actual "<expectedtitle>"
    And In home page verify if Enquiries and Enquiry in the main menu
    When Clicked on menu item "<MainMenuItem>" and submenu "<SubMenuItem>"
    Then Verify if the web page submenu title is "<expectedenqtitle>"
    When Parent First Name "<ParentFirstName>" Parent Second Name "<ParentSecondName>" Address "<Address>" Postcode "<Postcode>" MobileNumber "<MobileNumber>" Email id "<EmailId>"
    When The source is selected as "<Source>"
    When The First Child First Name "<FirstChildFirstName>" First Child Second Name "<SecondChildSecondName>" First Child DOB "<DOB>" Gender "<FirstChildGender>" Enrolment Start Date "<FirstEnrolmentStartDate>"
    When First child Booking Patten is "<BookingPatten>"
    When The Second Child First Name "<SecondChildFirstName>" Second Child Second Name "<SecondChildSecondName>" First Child DOB "<SecondChildDOB>" Gender "<SecondChildGender>" Enrolment Start Date "<SecondEnrolmentStartDate>"
    When Second Child Booking Patten is "<SecondBookingPatten>"
    Then Click on Add Enquiry
    Then Submit General Notes "<ParentName>"
    When Verify if user can add a visit with visit date "<VisitDate>" and visit time "<VisitTime>" with main comment "<ParentSecondName>"
    Then Logout from redfish and close browser

    Examples: 
      | UserName    | Password  | application | expectedtitle | MainMenuItem | SubMenuItem | expectedenqtitle | ParentFirstName | ParentSecondName | ParentName        | Address               | Postcode | MobileNumber | EmailId                    | Source     | FirstChildFirstName | SecondChildSecondName | DOB        | FirstChildGender | FirstEnrolmentStartDate | FirstEnrolmentEndDate | BookingPatten                   | SecondChildFirstName | SecondChildSecondName | SecondChildDOB | SecondChildGender | SecondEnrolmentStartDate | SecondBookingPatten             | EnquiryDetails  | Sibling | Relationship | ParentalResponsibility | PhotoPreference | TFCReference | LEAFEETReference | hrFundingCode | ChildProfileTitle | VisitDate  | VisitTime |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Arielle         | Sevin            | Arielle Sevin     | 12 Charing Cross Park | SO54 0LG |  07340997318 | asevinax@amazon.com        | BH Website | Arly                | Sevin                 | 15/01/2019 | M                | 01/04/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW FAM FPM | Nara                 | Sevin                 | 15/01/2020     | F                 | 01/04/2021               | AMM PMM AMT PMT AMW PMW FAM FPM | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Jelene          | Gallop           | Jelene Gallop     | 349 Harper Center     | SO55 0LG |  07400593503 | jgallopay@foxnews.com      | BH Website | Jinny               | Gallop                | 15/01/2019 | M                | 01/04/2021              | 12/12/2022            | All Days                        | Emelyne              | Gallop                | 15/01/2020     | F                 | 01/04/2021               | AMM PMM AMT PMT AMW PMW FAM FPM | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Odo             | Estcot           | Odo Estcot        | 8294 Jana Drive       | SO56 0LG |  07888839990 | oestcotaz@paginegialle.com | BH Website | Christiane          | Estcot                | 28/10/2019 | M                | 01/04/2021              | 12/12/2022            | AMM AMT PMT AMW PMW THAM THPM   | Ali                  | Estcot                | 15/01/2020     | F                 | 01/04/2021               | AMM AMT PMT AMW PMW THAM THPM   | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Donella         | Checo            | Donella Checo     | 081 Tennessee Circle  | SO57 0LG |  07308277463 | dchecob0@narod.com         | BH Website | Em                  | Checo                 | 15/01/2019 | M                | 01/04/2021              | 12/12/2022            | AMM PMM AMT PMT FAM FPM         | Willy                | Checo                 | 15/01/2020     | M                 | 01/04/2021               | AMM PMM AMT PMT FAM FPM         | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Nance           | Odlin            | Nance Odlin       | 9756 Moland Drive     | SO54 0LG |  07605686953 | nodlinb1@youku.com         | BH Website | Ingrim              | Odlin                 | 15/01/2019 | F                | 01/04/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW FAM FPM | Dorree               | Odlin                 | 15/01/2020     | M                 | 01/04/2021               | AMM PMM AMT PMT AMW PMW FAM FPM | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Aleksandr       | Gerauld          | Aleksandr Gerauld | 00 Iowa Parkway       | SO55 0LG |  07873993947 | agerauldb2@jugem.com       | BH Website | Nance               | Gerauld               | 15/01/2019 | M                | 01/04/2021              | 12/12/2022            | All Days                        | Latia                | Gerauld               | 15/01/2020     | F                 | 01/04/2021               | AMM PMM AMT PMT AMW PMW FAM FPM | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Anatol          | Entwistle        | Anatol Entwistle  | 7287 Daystar Place    | SO56 0LG |  07802701193 | aentwistleb3@un.com        | BH Website | Renelle             | Entwistle             | 28/10/2019 | F                | 01/04/2021              | 12/12/2022            | AMM AMT PMT AMW PMW THAM THPM   | Robbie               | Entwistle             | 15/01/2020     | F                 | 01/04/2021               | AMM AMT PMT AMW PMW THAM THPM   | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Bridgette       | Cothey           | Bridgette Cothey  | 69 Maple Hill         | SO57 0LG |  07586275711 | bcotheyb4@hao123.com       | BH Website | Immanuel            | Cothey                | 15/01/2019 | M                | 01/04/2021              | 12/12/2022            | AMM PMM AMT PMT FAM FPM         | Tiphany              | Cothey                | 15/01/2020     | M                 | 01/04/2021               | AMM PMM AMT PMT FAM FPM         | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Rees            | Slade            | Rees Slade        | 57 Starling Pass      | SO54 0LG |  07439243157 | rsladeb5@ehow.com          | BH Website | Randal              | Slade                 | 15/01/2019 | F                | 01/04/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW FAM FPM | Clayborn             | Slade                 | 15/01/2020     | M                 | 01/04/2021               | AMM PMM AMT PMT AMW PMW FAM FPM | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Chelsae         | Hourston         | Chelsae Hourston  | 7801 Fair Oaks Court  | SO55 0LG |  07911012227 | chourstonb6@woothemes.com  | BH Website | Dev                 | Hourston              | 15/01/2019 | F                | 01/04/2021              | 12/12/2022            | All Days                        | Upton                | Hourston              | 15/01/2020     | M                 | 01/04/2021               | AMM PMM AMT PMT FAM FPM         | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Doralynn        | Oswal            | Doralynn Oswal    | 6054 Elgar Alley      | SO56 0LG |  07207036279 | doswalb7@qq.com            | BH Website | Alric               | Oswal                 | 28/10/2019 | F                | 01/04/2021              | 12/12/2022            | AMM AMT PMT AMW PMW THAM THPM   | Lew                  | Oswal                 | 15/01/2020     | M                 | 01/04/2021               | AMM AMT PMT AMW PMW THAM THPM   | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Elbert          | Calwell          | Elbert Calwell    | 2 Mesta Terrace       | SO57 0LG |  07577152154 | ecalwellb8@goodreads.com   | BH Website | Raviv               | Calwell               | 15/01/2019 | F                | 01/04/2021              | 12/12/2022            | AMM PMM AMT PMT FAM FPM         | Blondie              | Calwell               | 15/01/2020     | M                 | 01/04/2021               | AMM PMM AMT PMT FAM FPM         | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
