Feature: 03.2 Register Children

  @RegisterOneChild @reg22/04/2021 @Bug-2591
  Scenario Outline: Verify if user is able to register first child
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify if the web page title actual "<expectedtitle>"
    Then Verify search functionality with only Parent Name "<EmailId>" in search page
    Then Verify Enquiry search functionality with only Parent Name "<EmailId>" in search page
    When Clicked on register First child with sibling with "<Sibling>"
    When Selecting the Relationship status as "<Relationship>" and Parental Parental Responsibility as "<ParentalResponsibility>"
    When Selecting the PhotoPreference as "<PhotoPreference>"
    When The TFC Reference "<TFCReference>" and LEAFEETReference "<LEAFEETReference>" and hrFundingCode "<hrFundingCode>"
    When The Enrolment Leave date is "<FirstEnrolmentEndDate>"
    Then Verify if the child is registered "<ChildProfileTitle>"
    Then Logout from redfish and close browser

    Examples: 
      | UserName    | Password  | application | expectedtitle | MainMenuItem | SubMenuItem | expectedenqtitle | ParentFirstName | ParentSecondName | ParentName     | Address              | Postcode | MobileNumber | EmailId                  | Source     | FirstChildFirstName | SecondChildSecondName | DOB        | FirstChildGender | FirstEnrolmentStartDate | FirstEnrolmentEndDate | BookingPatten                   | SecondChildFirstName | SecondChildSecondName | SecondChildDOB | SecondChildGender | SecondEnrolmentStartDate | SecondBookingPatten             | EnquiryDetails  | Sibling | Relationship | ParentalResponsibility | PhotoPreference | TFCReference | LEAFEETReference | hrFundingCode | ChildProfileTitle | VisitDate  | VisitTime |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Nessi           | Caberas          | Nessi Caberas  | 977 Hanson Avenue    | SO60 0LG |  07641570156 | ncaberasby@bloglines.com | BH Website | Annabel             | Caberas               | 27/04/2019 | M                | 19/04/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW FAM FPM | Nara                 | Caberas               | 15/01/2020     | F                 | 01/04/2021               | AMM PMM AMT PMT AMW PMW FAM FPM | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Liane           | Aleshkov         | Liane Aleshkov | 392 Sutherland Trail | SO61 0LG |  07169091544 | laleshkovbz@slashdot.com | BH Website | Aloysius            | Aleshkov              | 28/09/2019 | M                | 01/04/2021              | 12/12/2022            | All Days                        | Emelyne              | Aleshkov              | 15/01/2020     | F                 | 01/04/2021               | AMM PMM AMT PMT AMW PMW FAM FPM | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Bron            | Rumens           | Bron Rumens    | 63699 Erie Park      | SO62 0LG |  07680691347 | brumensc0@bloomberg.com  | BH Website | Inger               | Rumens                | 29/02/2018 | F                | 01/04/2021              | 12/12/2022            | AMM AMT PMT AMW PMW THAM THPM   | Ali                  | Rumens                | 15/01/2020     | F                 | 01/04/2021               | AMM AMT PMT AMW PMW THAM THPM   | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |

  @Register @2ndRegister @Register @reg22/04/2021
  Scenario Outline: Verify if user is able to register the 2nd Child
    Given Initialize the browser with chrome
    And Open Web Application "<application>"
    When User enters User Name "<UserName>" and Password "<Password>"
    Then Verify if the web page title actual "<expectedtitle>"
    Then Verify search functionality with only Parent Name "<EmailId>" in search page
    Then Verify Enquiry search functionality with only Parent Name "<EmailId>" in search page
    When Clicked on register Second child with sibling "<Sibling>"
    When Selecting the Relationship status as "<Relationship>" and Parental Parental Responsibility as "<ParentalResponsibility>"
    When Selecting the PhotoPreference as "<PhotoPreference>"
    When The TFC Reference "<TFCReference>" and LEAFEETReference "<LEAFEETReference>" and hrFundingCode "<hrFundingCode>"
    When The Enrolment Leave date is "<FirstEnrolmentEndDate>"
    Then Verify if the child is registered "<ChildProfileTitle>"
    Then Logout from redfish and close browser

    Examples: 
      | UserName    | Password  | application | expectedtitle | MainMenuItem | SubMenuItem | expectedenqtitle | ParentFirstName | ParentSecondName | ParentName        | Address              | Postcode | MobileNumber | EmailId                   | Source     | FirstChildFirstName | SecondChildSecondName | DOB        | FirstChildGender | FirstEnrolmentStartDate | FirstEnrolmentEndDate | BookingPatten                   | SecondChildFirstName | SecondChildSecondName | SecondChildDOB | SecondChildGender | SecondEnrolmentStartDate | SecondBookingPatten             | EnquiryDetails  | Sibling | Relationship | ParentalResponsibility | PhotoPreference | TFCReference | LEAFEETReference | hrFundingCode | ChildProfileTitle | VisitDate  | VisitTime |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Aleksandr       | Gerauld          | Aleksandr Gerauld | 00 Iowa Parkway      | SO55 0LG |  07873993947 | agerauldb2@jugem.com      | BH Website | Nance               | Gerauld               | 15/01/2019 | M                | 01/04/2021              | 12/12/2022            | All Days                        | Latia                | Gerauld               | 15/01/2020     | F                 | 01/04/2021               | AMM PMM AMT PMT AMW PMW FAM FPM | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Anatol          | Entwistle        | Anatol Entwistle  | 7287 Daystar Place   | SO56 0LG |  07802701193 | aentwistleb3@un.com       | BH Website | Renelle             | Entwistle             | 28/10/2019 | F                | 01/04/2021              | 12/12/2022            | AMM AMT PMT AMW PMW THAM THPM   | Robbie               | Entwistle             | 15/01/2020     | F                 | 01/04/2021               | AMM AMT PMT AMW PMW THAM THPM   | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Bridgette       | Cothey           | Bridgette Cothey  | 69 Maple Hill        | SO57 0LG |  07586275711 | bcotheyb4@hao123.com      | BH Website | Immanuel            | Cothey                | 15/01/2019 | M                | 01/04/2021              | 12/12/2022            | AMM PMM AMT PMT FAM FPM         | Tiphany              | Cothey                | 15/01/2020     | M                 | 01/04/2021               | AMM PMM AMT PMT FAM FPM         | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Rees            | Slade            | Rees Slade        | 57 Starling Pass     | SO54 0LG |  07439243157 | rsladeb5@ehow.com         | BH Website | Randal              | Slade                 | 15/01/2019 | F                | 01/04/2021              | 12/12/2022            | AMM PMM AMT PMT AMW PMW FAM FPM | Clayborn             | Slade                 | 15/01/2020     | M                 | 01/04/2021               | AMM PMM AMT PMT AMW PMW FAM FPM | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Chelsae         | Hourston         | Chelsae Hourston  | 7801 Fair Oaks Court | SO55 0LG |  07911012227 | chourstonb6@woothemes.com | BH Website | Dev                 | Hourston              | 15/01/2019 | F                | 01/04/2021              | 12/12/2022            | All Days                        | Upton                | Hourston              | 15/01/2020     | M                 | 01/04/2021               | AMM PMM AMT PMT FAM FPM         | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM  | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Doralynn        | Oswal            | Doralynn Oswal    | 6054 Elgar Alley     | SO56 0LG |  07207036279 | doswalb7@qq.com           | BH Website | Alric               | Oswal                 | 28/10/2019 | F                | 01/04/2021              | 12/12/2022            | AMM AMT PMT AMW PMW THAM THPM   | Lew                  | Oswal                 | 15/01/2020     | M                 | 01/04/2021               | AMM AMT PMT AMW PMW THAM THPM   | Enquiry Details | No      | Mother       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
      | 99160101NM2 | Password1 | redfishUAT  | Home          | Enquiries    | Enquiry     | New enquiry      | Elbert          | Calwell          | Elbert Calwell    | 2 Mesta Terrace      | SO57 0LG |  07577152154 | ecalwellb8@goodreads.com  | BH Website | Raviv               | Calwell               | 15/01/2019 | F                | 01/04/2021              | 12/12/2022            | AMM PMM AMT PMT FAM FPM         | Blondie              | Calwell               | 15/01/2020     | M                 | 01/04/2021               | AMM PMM AMT PMT FAM FPM         | Enquiry Details | No      | Father       | Yes                    | All             | DAST25417TFC | MIOS62392TFC     |   50700000013 | Child             | 29/04/2020 |      0930 |
